ServerEvents.recipes(e => {
    // Base Crystals    
    e.shapeless('actuallyadditions:empowered_enori_crystal', ['9x actuallyadditions:empowered_enori_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_enori_crystal_shard', ['actuallyadditions:empowered_enori_crystal'])
    e.shapeless('actuallyadditions:empowered_emeradic_crystal', ['9x actuallyadditions:empowered_emeradic_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_emeradic_crystal_shard', ['actuallyadditions:empowered_emeradic_crystal'])
    e.shapeless('actuallyadditions:empowered_void_crystal', ['9x actuallyadditions:empowered_void_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_void_crystal_shard', ['actuallyadditions:empowered_void_crystal'])
    e.shapeless('actuallyadditions:empowered_diamatine_crystal', ['9x actuallyadditions:empowered_diamatine_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_diamatine_crystal_shard', ['actuallyadditions:empowered_diamatine_crystal'])
    e.shapeless('actuallyadditions:empowered_palis_crystal', ['9x actuallyadditions:empowered_palis_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_palis_crystal_shard', ['actuallyadditions:empowered_palis_crystal'])
    e.shapeless('actuallyadditions:empowered_restonia_crystal', ['9x actuallyadditions:empowered_restonia_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_restonia_crystal_shard', ['actuallyadditions:empowered_restonia_crystal'])
    // Zartiq
    e.shapeless('actuallyadditions:zartiq_crystal', ['9x actuallyadditions:zartiq_crystal_shard'])
    e.shapeless('9x actuallyadditions:zartiq_crystal_shard', ['actuallyadditions:zartiq_crystal'])
    e.shapeless('actuallyadditions:zartiq_crystal_block', ['9x actuallyadditions:zartiq_crystal'])
    e.shapeless('9x actuallyadditions:zartiq_crystal', ['actuallyadditions:zartiq_crystal_block'])
    e.shapeless('actuallyadditions:empowered_zartiq_crystal', ['9x actuallyadditions:empowered_zartiq_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_zartiq_crystal_shard', ['actuallyadditions:empowered_zartiq_crystal'])
    e.shapeless('actuallyadditions:empowered_zartiq_crystal_block', ['9x actuallyadditions:empowered_zartiq_crystal'])
    e.shapeless('9x actuallyadditions:empowered_zartiq_crystal', ['actuallyadditions:empowered_zartiq_crystal_block'])
    // Inerthet
    e.shapeless('actuallyadditions:inerthet_crystal', ['9x actuallyadditions:inerthet_crystal_shard'])
    e.shapeless('9x actuallyadditions:inerthet_crystal_shard', ['actuallyadditions:inerthet_crystal'])
    e.shapeless('actuallyadditions:inerthet_crystal_block', ['9x actuallyadditions:inerthet_crystal'])
    e.shapeless('9x actuallyadditions:inerthet_crystal', ['actuallyadditions:inerthet_crystal_block'])
    e.shapeless('actuallyadditions:empowered_inerthet_crystal', ['9x actuallyadditions:empowered_inerthet_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_inerthet_crystal_shard', ['actuallyadditions:empowered_inerthet_crystal'])
    e.shapeless('actuallyadditions:empowered_inerthet_crystal_block', ['9x actuallyadditions:empowered_inerthet_crystal'])
    e.shapeless('9x actuallyadditions:empowered_inerthet_crystal', ['actuallyadditions:empowered_inerthet_crystal_block'])
    // Zerbonkys
    e.shapeless('actuallyadditions:zerbonkys_crystal', ['9x actuallyadditions:zerbonkys_crystal_shard'])
    e.shapeless('9x actuallyadditions:zerbonkys_crystal_shard', ['actuallyadditions:zerbonkys_crystal'])
    e.shapeless('actuallyadditions:zerbonkys_crystal_block', ['9x actuallyadditions:zerbonkys_crystal'])
    e.shapeless('9x actuallyadditions:zerbonkys_crystal', ['actuallyadditions:zerbonkys_crystal_block'])
    e.shapeless('actuallyadditions:empowered_zerbonkys_crystal', ['9x actuallyadditions:empowered_zerbonkys_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_zerbonkys_crystal_shard', ['actuallyadditions:empowered_zerbonkys_crystal'])
    e.shapeless('actuallyadditions:empowered_zerbonkys_crystal_block', ['9x actuallyadditions:empowered_zerbonkys_crystal'])
    e.shapeless('9x actuallyadditions:empowered_zerbonkys_crystal', ['actuallyadditions:empowered_zerbonkys_crystal_block'])
    // Zerbon
    e.shapeless('actuallyadditions:zerbon_crystal', ['9x actuallyadditions:zerbon_crystal_shard'])
    e.shapeless('9x actuallyadditions:zerbon_crystal_shard', ['actuallyadditions:zerbon_crystal'])
    e.shapeless('actuallyadditions:zerbon_crystal_block', ['9x actuallyadditions:zerbon_crystal'])
    e.shapeless('9x actuallyadditions:zerbon_crystal', ['actuallyadditions:zerbon_crystal_block'])
    e.shapeless('actuallyadditions:empowered_zerbon_crystal', ['9x actuallyadditions:empowered_zerbon_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_zerbon_crystal_shard', ['actuallyadditions:empowered_zerbon_crystal'])
    e.shapeless('actuallyadditions:empowered_zerbon_crystal_block', ['9x actuallyadditions:empowered_zerbon_crystal'])
    e.shapeless('9x actuallyadditions:empowered_zerbon_crystal', ['actuallyadditions:empowered_zerbon_crystal_block'])
    // Lectruma
    e.shapeless('actuallyadditions:lectruma_crystal', ['9x actuallyadditions:lectruma_crystal_shard'])
    e.shapeless('9x actuallyadditions:lectruma_crystal_shard', ['actuallyadditions:lectruma_crystal'])
    e.shapeless('actuallyadditions:lectruma_crystal_block', ['9x actuallyadditions:lectruma_crystal'])
    e.shapeless('9x actuallyadditions:lectruma_crystal', ['actuallyadditions:lectruma_crystal_block'])
    e.shapeless('actuallyadditions:empowered_lectruma_crystal', ['9x actuallyadditions:empowered_lectruma_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_lectruma_crystal_shard', ['actuallyadditions:empowered_lectruma_crystal'])
    e.shapeless('actuallyadditions:empowered_lectruma_crystal_block', ['9x actuallyadditions:empowered_lectruma_crystal'])
    e.shapeless('9x actuallyadditions:empowered_lectruma_crystal', ['actuallyadditions:empowered_lectruma_crystal_block'])
    // Uranima
    e.shapeless('actuallyadditions:uranima_crystal', ['9x actuallyadditions:uranima_crystal_shard'])
    e.shapeless('9x actuallyadditions:uranima_crystal_shard', ['actuallyadditions:uranima_crystal'])
    e.shapeless('actuallyadditions:uranima_crystal_block', ['9x actuallyadditions:uranima_crystal'])
    e.shapeless('9x actuallyadditions:uranima_crystal', ['actuallyadditions:uranima_crystal_block'])
    e.shapeless('actuallyadditions:empowered_uranima_crystal', ['9x actuallyadditions:empowered_uranima_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_uranima_crystal_shard', ['actuallyadditions:empowered_uranima_crystal'])
    e.shapeless('actuallyadditions:empowered_uranima_crystal_block', ['9x actuallyadditions:empowered_uranima_crystal'])
    e.shapeless('9x actuallyadditions:empowered_uranima_crystal', ['actuallyadditions:empowered_uranima_crystal_block'])
    // Mosium
    e.shapeless('actuallyadditions:mosium_crystal', ['9x actuallyadditions:mosium_crystal_shard'])
    e.shapeless('9x actuallyadditions:mosium_crystal_shard', ['actuallyadditions:mosium_crystal'])
    e.shapeless('actuallyadditions:mosium_crystal_block', ['9x actuallyadditions:mosium_crystal'])
    e.shapeless('9x actuallyadditions:mosium_crystal', ['actuallyadditions:mosium_crystal_block'])
    e.shapeless('actuallyadditions:empowered_mosium_crystal', ['9x actuallyadditions:empowered_mosium_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_mosium_crystal_shard', ['actuallyadditions:empowered_mosium_crystal'])
    e.shapeless('actuallyadditions:empowered_mosium_crystal_block', ['9x actuallyadditions:empowered_mosium_crystal'])
    e.shapeless('9x actuallyadditions:empowered_mosium_crystal', ['actuallyadditions:empowered_mosium_crystal_block'])
    // Richoum
    e.shapeless('actuallyadditions:richoum_crystal', ['9x actuallyadditions:richoum_crystal_shard'])
    e.shapeless('9x actuallyadditions:richoum_crystal_shard', ['actuallyadditions:richoum_crystal'])
    e.shapeless('actuallyadditions:richoum_crystal_block', ['9x actuallyadditions:richoum_crystal'])
    e.shapeless('9x actuallyadditions:richoum_crystal', ['actuallyadditions:richoum_crystal_block'])
    e.shapeless('actuallyadditions:empowered_richoum_crystal', ['9x actuallyadditions:empowered_richoum_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_richoum_crystal_shard', ['actuallyadditions:empowered_richoum_crystal'])
    e.shapeless('actuallyadditions:empowered_richoum_crystal_block', ['9x actuallyadditions:empowered_richoum_crystal'])
    e.shapeless('9x actuallyadditions:empowered_richoum_crystal', ['actuallyadditions:empowered_richoum_crystal_block'])
    // Mythase
    e.shapeless('actuallyadditions:mythase_crystal', ['9x actuallyadditions:mythase_crystal_shard'])
    e.shapeless('9x actuallyadditions:mythase_crystal_shard', ['actuallyadditions:mythase_crystal'])
    e.shapeless('actuallyadditions:mythase_crystal_block', ['9x actuallyadditions:mythase_crystal'])
    e.shapeless('9x actuallyadditions:mythase_crystal', ['actuallyadditions:mythase_crystal_block'])
    e.shapeless('actuallyadditions:empowered_mythase_crystal', ['9x actuallyadditions:empowered_mythase_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_mythase_crystal_shard', ['actuallyadditions:empowered_mythase_crystal'])
    e.shapeless('actuallyadditions:empowered_mythase_crystal_block', ['9x actuallyadditions:empowered_mythase_crystal'])
    e.shapeless('9x actuallyadditions:empowered_mythase_crystal', ['actuallyadditions:empowered_mythase_crystal_block'])
    // Enori
    e.shapeless('actuallyadditions:surcea_crystal', ['9x actuallyadditions:surcea_crystal_shard'])
    e.shapeless('9x actuallyadditions:surcea_crystal_shard', ['actuallyadditions:surcea_crystal'])
    e.shapeless('actuallyadditions:surcea_crystal_block', ['9x actuallyadditions:surcea_crystal'])
    e.shapeless('9x actuallyadditions:surcea_crystal', ['actuallyadditions:surcea_crystal_block'])
    e.shapeless('actuallyadditions:empowered_surcea_crystal', ['9x actuallyadditions:empowered_surcea_crystal_shard'])
    e.shapeless('9x actuallyadditions:empowered_surcea_crystal_shard', ['actuallyadditions:empowered_surcea_crystal'])
    e.shapeless('actuallyadditions:empowered_surcea_crystal_block', ['9x actuallyadditions:empowered_surcea_crystal'])
    e.shapeless('9x actuallyadditions:empowered_surcea_crystal', ['actuallyadditions:empowered_surcea_crystal_block'])
    // Lamps
    e.shaped('actuallyadditions:lamp_white', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:enori_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_orange', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:zerbon_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_magenta', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:mythase_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_light_blue', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:diamatine_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_yellow', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:lectruma_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_lime', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:uranima_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_pink', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:surcea_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_gray', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:inerthet_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_light_gray', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:zartiq_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_cyan', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:mosium_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_purple', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:richoum_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_blue', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:palis_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_brown', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:zerbonkys_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_green', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:emeradic_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_red', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:restonia_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
    e.shaped('actuallyadditions:lamp_black', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:void_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
})