ServerEvents.recipes(e => {
    function lasering(input, output, energy) {
        e.custom({ "type": "actuallyadditions:laser", "energy": energy, "ingredient": { "item": input }, "result": { "id": output } })
    }
    lasering('minecraft:quartz', 'actuallyadditions:zartiq_crystal', 60)
    lasering('minecraft:smooth_quartz', 'actuallyadditions:zartiq_crystal_block', 600)
    lasering('minecraft:netherite_ingot', 'actuallyadditions:inerthet_crystal', 60)
    lasering('minecraft:netherite_block', 'actuallyadditions:inerthet_crystal_block', 600)
    lasering('megacells:sky_bronze_ingot', 'actuallyadditions:zerbonkys_crystal', 60)
    lasering('megacells:sky_bronze_block', 'actuallyadditions:zerbonkys_crystal_block', 600)
    lasering('mekanism:ingot_bronze', 'actuallyadditions:zerbon_crystal', 60)
    lasering('mekanism:block_bronze', 'actuallyadditions:zerbon_crystal_block', 600)
    lasering('createaddition:electrum_ingot', 'actuallyadditions:lectruma_crystal', 60)
    lasering('createaddition:electrum_block', 'actuallyadditions:lectruma_crystal_block', 600)
    lasering('mekanism:ingot_uranium', 'actuallyadditions:uranima_crystal', 60)
    lasering('mekanism:block_uranium', 'actuallyadditions:uranima_crystal_block', 600)
    lasering('mekanism:ingot_osmium', 'actuallyadditions:mosium_crystal', 60)
    lasering('mekanism:block_osmium', 'actuallyadditions:mosium_crystal_block', 600)
    lasering('createcasing:chorium_ingot', 'actuallyadditions:richoum_crystal', 60)
    lasering('createcasing:chorium_block', 'actuallyadditions:richoum_crystal_block', 600)
    lasering('minecraft:amethyst_shard', 'actuallyadditions:mythase_crystal', 60)
    lasering('minecraft:amethyst_block', 'actuallyadditions:mythase_crystal_block', 600)
    lasering('ars_nouveau:source_gem', 'actuallyadditions:surcea_crystal', 60)
    lasering('ars_nouveau:source_gem_block', 'actuallyadditions:surcea_crystal_block', 600)
})