ServerEvents.recipes(e => {
  // Electrum
  e.shapeless('createaddition:electrum_block', '9x createaddition:electrum_ingot')
  e.shapeless('9x createaddition:electrum_ingot', 'createaddition:electrum_block')
  // Chorium
  e.shaped('createcasing:chorium_block', ['AA', 'AA'], { 'A': 'createcasing:chorium_ingot' })
  e.shapeless('4x createcasing:chorium_ingot', ['createcasing:chorium_block'])
  // Alloys
  e.shaped('create:stone_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:stone_alloy' })
  e.shapeless('9x create:stone_alloy', ['create:stone_alloy_block'])
  e.shaped('create:brass_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:brass_alloy' })
  e.shapeless('9x create:brass_alloy', ['create:brass_alloy_block'])
  e.shaped('create:copper_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:copper_alloy' })
  e.shapeless('9x create:copper_alloy', ['create:copper_alloy_block'])
  e.shaped('create:granite_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:granite_alloy' })
  e.shapeless('9x create:granite_alloy', ['create:granite_alloy_block'])
  e.shaped('create:diorite_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:diorite_alloy' })
  e.shapeless('9x create:diorite_alloy', ['create:diorite_alloy_block'])
  e.shaped('create:tuff_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:tuff_alloy' })
  e.shapeless('9x create:tuff_alloy', ['create:tuff_alloy_block'])
  e.shaped('create:deepslate_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:deepslate_alloy' })
  e.shapeless('9x create:deepslate_alloy', ['create:deepslate_alloy_block'])
  e.shaped('create:blackstone_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:blackstone_alloy' })
  e.shapeless('9x create:blackstone_alloy', ['create:blackstone_alloy_block'])
  e.shaped('create:basalt_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:basalt_alloy' })
  e.shapeless('9x create:basalt_alloy', ['create:basalt_alloy_block'])
  e.shaped('create:source_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:source_alloy' })
  e.shapeless('9x create:source_alloy', ['create:source_alloy_block'])
  e.shaped('create:chorus_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:chorus_alloy' })
  e.shapeless('9x create:chorus_alloy', ['create:chorus_alloy_block'])
  e.shaped('create:iron_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:iron_alloy' })
  e.shapeless('9x create:iron_alloy', ['create:iron_alloy_block'])
  e.shaped('create:zinc_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:zinc_alloy' })
  e.shapeless('9x create:zinc_alloy', ['create:zinc_alloy_block'])
  e.shaped('create:gold_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:gold_alloy' })
  e.shapeless('9x create:gold_alloy', ['create:gold_alloy_block'])
  e.shaped('create:tin_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:tin_alloy' })
  e.shapeless('9x create:tin_alloy', ['create:tin_alloy_block'])
  e.shaped('create:lead_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:lead_alloy' })
  e.shapeless('9x create:lead_alloy', ['create:lead_alloy_block'])
  e.shaped('create:osmium_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:osmium_alloy' })
  e.shapeless('9x create:osmium_alloy', ['create:osmium_alloy_block'])
  e.shaped('create:electrum_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:electrum_alloy' })
  e.shapeless('9x create:electrum_alloy', ['create:electrum_alloy_block'])
  e.shaped('create:uranium_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:uranium_alloy' })
  e.shapeless('9x create:uranium_alloy', ['create:uranium_alloy_block'])
  e.shaped('create:netherite_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:netherite_alloy' })
  e.shapeless('9x create:netherite_alloy', ['create:netherite_alloy_block'])
  e.shaped('create:red_iron_alloy_block', ['AAA', 'AAA', 'AAA'], { 'A': 'create:red_iron_alloy' })
  e.shapeless('9x create:red_iron_alloy', ['create:red_iron_alloy_block'])
  e.shaped('create:millstone', ['A', 'B', 'C'], { 'A': 'createcasing:stone_cogwheel', 'B': 'create:stone_alloy_block', 'C': 'minecraft:stone' })
})
