ServerEvents.recipes(e => {
    // Cells
    e.shaped('ae2:cell_component_1k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_mosium_crystal_shard', 'B': 'ae2:charged_certus_quartz_crystal', 'C': 'ae2:quartz_vibrant_glass' })
    e.shaped('ae2:cell_component_4k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_zartiq_crystal_shard', 'B': 'ae2:cell_component_1k', 'C': 'ae2:logic_processor' })
    e.shaped('ae2:cell_component_16k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_inerthet_crystal_shard', 'B': 'ae2:cell_component_4k', 'C': 'ae2:calculation_processor' })
    e.shaped('ae2:cell_component_64k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_zerbonkys_crystal_shard', 'B': 'ae2:cell_component_16k', 'C': 'ae2:engineering_processor' })
    e.shaped('ae2:cell_component_256k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_zerbon_crystal_shard', 'B': 'ae2:cell_component_64k', 'C': 'extendedae:concurrent_processor' })
    e.shaped('megacells:cell_component_1m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_lectruma_crystal_shard', 'B': 'ae2:cell_component_256k', 'C': 'megacells:accumulation_processor' })
    e.shaped('megacells:cell_component_4m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_uranima_crystal_shard', 'B': 'megacells:cell_component_1m', 'C': 'ae2:logic_processor' })
    e.shaped('megacells:cell_component_16m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_richoum_crystal_shard', 'B': 'megacells:cell_component_4m', 'C': 'ae2:calculation_processor' })
    e.shaped('megacells:cell_component_64m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_mythase_crystal_shard', 'B': 'megacells:cell_component_16m', 'C': 'ae2:engineering_processor' })
    e.shaped('megacells:cell_component_256m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_surcea_crystal_shard', 'B': 'megacells:cell_component_64m', 'C': 'extendedae:concurrent_processor' })
    e.shaped('advanced_ae:quantum_storage_component', ['ABA', 'BCB', 'ABA'], { 'A': 'ae2:spatial_cell_component_128', 'B': 'megacells:cell_component_256m', 'C': 'advanced_ae:quantum_processor' })
    e.shaped('ae2:spatial_cell_housing', ['ABA', 'B B', 'CCC'], { 'A': 'ae2:quartz_vibrant_glass', 'B': 'minecraft:glowstone_dust', 'C': 'mekanism:ingot_steel' })
    e.shaped('megacells:bulk_item_cell_housing', ['ABA', 'B B', 'CCC'], { 'A': 'ae2:quartz_vibrant_glass', 'B': 'ae2:sky_dust', 'C': 'minecraft:netherite_ingot' })
    e.shaped('megacells:radioactive_chemical_cell_housing', ['ABA', 'B B', 'CDC'], { 'A': 'mekanismgenerators:reactor_glass', 'B': 'ae2:sky_dust', 'C': 'mekanism:hdpe_sheet', 'D': 'mekanism:block_polonium' })
    e.shapeless('ae2:portable_item_cell_housing', ['ae2:item_cell_housing', 'ae2:chest', 'ae2:energy_cell'])
    e.shapeless('ae2:portable_fluid_cell_housing', ['ae2:fluid_cell_housing', 'ae2:chest', 'ae2:energy_cell'])
    e.shapeless('appmek:portable_chemical_cell_housing', ['appmek:chemical_cell_housing', 'ae2:chest', 'ae2:energy_cell'])
    e.shapeless('arseng:portable_source_cell_housing', ['arseng:source_cell_housing', 'ae2:chest', 'ae2:energy_cell'])
    e.shapeless('megacells:portable_item_cell_housing', ['megacells:mega_item_cell_housing', 'ae2:chest', 'ae2:dense_energy_cell'])
    e.shapeless('megacells:portable_fluid_cell_housing', ['megacells:mega_fluid_cell_housing', 'ae2:chest', 'ae2:dense_energy_cell'])
    e.shapeless('megacells:portable_chemical_cell_housing', ['megacells:mega_chemical_cell_housing', 'ae2:chest', 'ae2:dense_energy_cell'])
    e.shapeless('megacells:portable_source_cell_housing', ['megacells:mega_source_cell_housing', 'ae2:chest', 'ae2:dense_energy_cell'])
    e.shapeless('megacells:portable_cell_workbench', ['ae2:item_cell_housing', 'ae2:cell_workbench', 'ae2:singularity'])
})