
ServerEvents.recipes(event => {
        //---------------Removes---------------//


        //---------------Changing Ingrdient---------------//

        //---------------Adding Recipes---------------//

        // Alloys
        event.shaped(Item.of('create:stone_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:stone_alloy' })
        event.shapeless('9x create:stone_alloy', ['create:stone_alloy_block'])
        event.shaped(Item.of('create:brass_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:brass_alloy' })
        event.shapeless('9x create:brass_alloy', ['create:brass_alloy_block'])
        event.shaped(Item.of('create:copper_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:copper_alloy' })
        event.shapeless('9x create:copper_alloy', ['create:copper_alloy_block'])
        event.shaped(Item.of('create:granite_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:granite_alloy' })
        event.shapeless('9x create:granite_alloy', ['create:granite_alloy_block'])
        event.shaped(Item.of('create:diorite_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:diorite_alloy' })
        event.shapeless('9x create:diorite_alloy', ['create:diorite_alloy_block'])
        event.shaped(Item.of('create:tuff_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:tuff_alloy' })
        event.shapeless('9x create:tuff_alloy', ['create:tuff_alloy_block'])
        event.shaped(Item.of('create:deepslate_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:deepslate_alloy' })
        event.shapeless('9x create:deepslate_alloy', ['create:deepslate_alloy_block'])
        event.shaped(Item.of('create:blackstone_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:blackstone_alloy' })
        event.shapeless('9x create:blackstone_alloy', ['create:blackstone_alloy_block'])
        event.shaped(Item.of('create:basalt_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:basalt_alloy' })
        event.shapeless('9x create:basalt_alloy', ['create:basalt_alloy_block'])
        event.shaped(Item.of('create:source_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:source_alloy' })
        event.shapeless('9x create:source_alloy', ['create:source_alloy_block'])
        event.shaped(Item.of('create:chorus_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:chorus_alloy' })
        event.shapeless('9x create:chorus_alloy', ['create:chorus_alloy_block'])
        event.shaped(Item.of('create:iron_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:iron_alloy' })
        event.shapeless('9x create:iron_alloy', ['create:iron_alloy_block'])
        event.shaped(Item.of('create:zinc_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:zinc_alloy' })
        event.shapeless('9x create:zinc_alloy', ['create:zinc_alloy_block'])
        event.shaped(Item.of('create:gold_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:gold_alloy' })
        event.shapeless('9x create:gold_alloy', ['create:gold_alloy_block'])
        event.shaped(Item.of('create:tin_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:tin_alloy' })
        event.shapeless('9x create:tin_alloy', ['create:tin_alloy_block'])
        event.shaped(Item.of('create:lead_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:lead_alloy' })
        event.shapeless('9x create:lead_alloy', ['create:lead_alloy_block'])
        event.shaped(Item.of('create:osmium_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:osmium_alloy' })
        event.shapeless('9x create:osmium_alloy', ['create:osmium_alloy_block'])
        event.shaped(Item.of('create:electrum_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:electrum_alloy' })
        event.shapeless('9x create:electrum_alloy', ['create:electrum_alloy_block'])
        event.shaped(Item.of('create:uranium_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:uranium_alloy' })
        event.shapeless('9x create:uranium_alloy', ['create:uranium_alloy_block'])
        event.shaped(Item.of('create:netherite_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:netherite_alloy' })
        event.shapeless('9x create:netherite_alloy', ['create:netherite_alloy_block'])
        event.shaped(Item.of('create:shadow_steel_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:shadow_steel' })
        event.shapeless('9x create:shadow_steel', ['create:shadow_steel_block'])
        event.shaped(Item.of('create:refined_radiance_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:refined_radiance' })
        event.shapeless('9x create:refined_radiance', ['create:refined_radiance_block'])
        event.shaped(Item.of('create:red_iron_alloy_block'), ['AAA', 'AAA', 'AAA'], { 'A': 'create:red_iron_alloy' })
        event.shapeless('9x create:red_iron_alloy', ['create:red_iron_alloy_block'])

        event.shaped('create:millstone', ['A', 'B', 'C'], { 'A': 'createcasing:stone_cogwheel', 'B': 'create:stone_alloy_block', 'C': 'minecraft:stone' })

        // Dyes
        event.shaped('minecraft:dye_primer', ['A A', ' B '], { 'A': '#c:rods/wooden', 'B': '#minecraft:wooden_slabs' })
        event.shapeless('minecraft:white_dye', ['minecraft:dye_primer', 'minecraft:bone_meal', 'minecraft:bone_meal']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:white_dye', ['minecraft:dye_primer', 'minecraft:lily_of_the_valley']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:light_gray_dye', ['minecraft:dye_primer', 'minecraft:azure_bluet']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:light_gray_dye', ['minecraft:dye_primer', 'minecraft:oxeye_daisy']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:light_gray_dye', ['minecraft:dye_primer', 'minecraft:white_tulip']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:gray_dye', ['minecraft:dye_primer', 'minecraft:charcoal', 'minecraft:charcoal']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:black_dye', ['minecraft:dye_primer', 'minecraft:ink_sac', 'minecraft:ink_sac']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:black_dye', ['minecraft:dye_primer', 'minecraft:wither_rose']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:brown_dye', ['minecraft:dye_primer', 'minecraft:cocoa_beans', 'minecraft:cocoa_beans']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:red_dye', ['minecraft:dye_primer', 'minecraft:beetroot', 'minecraft:beetroot']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:red_dye', ['minecraft:dye_primer', 'minecraft:poppy']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:red_dye', ['minecraft:dye_primer', 'minecraft:red_tulip']).damageIngredient('minecraft:dye_primer')
        event.shapeless('2x minecraft:red_dye', ['minecraft:dye_primer', 'minecraft:rose_bush']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:orange_dye', ['minecraft:dye_primer', 'ars_nouveau:bombegranate_pod', 'ars_nouveau:bombegranate_pod']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:orange_dye', ['minecraft:dye_primer', 'ars_nouveau:wilden_spike', 'ars_nouveau:wilden_spike']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:orange_dye', ['minecraft:dye_primer', 'minecraft:orange_tulip']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:orange_dye', ['minecraft:dye_primer', 'minecraft:torchflower']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:yellow_dye', ['minecraft:dye_primer', '#c:dusts/sulfur', '#c:dusts/sulfur']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:yellow_dye', ['minecraft:dye_primer', 'minecraft:dandelion']).damageIngredient('minecraft:dye_primer')
        event.shapeless('2x minecraft:yellow_dye', ['minecraft:dye_primer', 'minecraft:sunflower']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:pink_dye', ['minecraft:dye_primer', 'ars_nouveau:magebloom', 'ars_nouveau:magebloom']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:pink_dye', ['minecraft:dye_primer', 'minecraft:pink_tulip']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:pink_dye', ['minecraft:dye_primer', 'minecraft:pink_petals']).damageIngredient('minecraft:dye_primer')
        event.shapeless('2x minecraft:pink_dye', ['minecraft:dye_primer', 'minecraft:peony']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:magenta_dye', ['minecraft:dye_primer', 'minecraft:allium']).damageIngredient('minecraft:dye_primer')
        event.shapeless('2x minecraft:magenta_dye', ['minecraft:dye_primer', 'minecraft:lilac']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:purple_dye', ['minecraft:dye_primer', 'ars_nouveau:sourceberry_bush', 'ars_nouveau:sourceberry_bush']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:purple_dye', ['minecraft:dye_primer', 'ars_nouveau:bastion_pod', 'ars_nouveau:bastion_pod']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:blue_dye', ['minecraft:dye_primer', 'minecraft:lapis_lazuli', 'minecraft:lapis_lazuli']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:blue_dye', ['minecraft:dye_primer', 'minecraft:cornflower']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:light_blue_dye', ['minecraft:dye_primer', 'ars_nouveau:frostaya_pod', 'ars_nouveau:frostaya_pod']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:light_blue_dye', ['minecraft:dye_primer', 'minecraft:blue_orchid']).damageIngredient('minecraft:dye_primer')
        event.shapeless('2x minecraft:cyan_dye', ['minecraft:dye_primer', 'minecraft:pitcher_plant']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:green_dye', ['minecraft:dye_primer', 'minecraft:cactus', 'minecraft:cactus']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:lime_dye', ['minecraft:dye_primer', 'ars_nouveau:mendosteen_pod', 'ars_nouveau:mendosteen_pod']).damageIngredient('minecraft:dye_primer')
        event.shapeless('minecraft:lime_dye', ['minecraft:dye_primer', 'minecraft:sea_pickle', 'minecraft:sea_pickle']).damageIngredient('minecraft:dye_primer')

        // Tools
        event.shaped(Item.of('minecraft:wooden_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:wooden_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:wooden_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:wooden_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:wooden_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:stone_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:stone_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:stone_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:stone_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:stone_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:iron_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
        event.shaped(Item.of('minecraft:iron_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
        event.shaped(Item.of('minecraft:iron_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
        event.shaped(Item.of('minecraft:iron_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
        event.shaped(Item.of('minecraft:iron_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
        event.shaped(Item.of('minecraft:golden_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:golden_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:golden_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:golden_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:golden_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:diamond_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:diamond_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:diamond_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:diamond_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:diamond_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:netherite_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:netherite_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:netherite_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:netherite_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('minecraft:netherite_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:nether_quartz_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:nether_quartz_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:nether_quartz_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:nether_quartz_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:nether_quartz_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:certus_quartz_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:certus_quartz_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:certus_quartz_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:certus_quartz_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:certus_quartz_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:fluix_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:fluix_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:fluix_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:fluix_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('ae2:fluix_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:bronze_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:bronze_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:bronze_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:bronze_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:bronze_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:lapis_lazuli_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:lapis_lazuli_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:lapis_lazuli_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:lapis_lazuli_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:lapis_lazuli_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:osmium_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:osmium_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:osmium_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:osmium_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:osmium_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_glowstone_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_glowstone_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_glowstone_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_glowstone_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_glowstone_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_obsidian_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_obsidian_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_obsidian_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_obsidian_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:refined_obsidian_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:steel_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:steel_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:steel_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:steel_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('mekanismtools:steel_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
        event.shaped(Item.of('naturesaura:infused_iron_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:infused_iron_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:infused_iron_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:infused_iron_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:infused_iron_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:sky_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:sky_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:sky_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:sky_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:sky_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:depth_sword'), ['A', 'A', 'B'], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:depth_pickaxe'), ['AAA', ' B ', ' B '], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:depth_axe'), ['AA', 'AB', ' B'], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:depth_shovel'), ['A', 'B', 'B'], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
        event.shaped(Item.of('naturesaura:depth_hoe'), ['AA', ' B', ' B'], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
        // Armors
        event.shaped(Item.of('create:cardboard_helmet'), ['AAA', 'A A'], { 'A': 'create:cardboard' })
        event.shaped(Item.of('create:cardboard_chestplate'), ['A A', 'AAA', 'AAA'], { 'A': 'create:cardboard' })
        event.shaped(Item.of('create:cardboard_leggings'), ['AAA', 'A A', 'A A'], { 'A': 'create:cardboard' })
        event.shaped(Item.of('create:cardboard_boots'), ['A A', 'A A'], { 'A': 'create:cardboard' })
        event.shaped(Item.of('minecraft:leather_helmet'), ['AAA', 'ABA'], { 'A': 'minecraft:leather', 'B': 'create:cardboard_helmet' })
        event.shaped(Item.of('minecraft:leather_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'minecraft:leather', 'B': 'create:cardboard_chestplate' })
        event.shaped(Item.of('minecraft:leather_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'minecraft:leather', 'B': 'create:cardboard_leggings' })
        event.shaped(Item.of('minecraft:leather_boots'), ['A A', 'ABA'], { 'A': 'minecraft:leather', 'B': 'create:cardboard_boots' })
        event.shaped(Item.of('mekanismtools:lapis_lazuli_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:leather_helmet' })
        event.shaped(Item.of('mekanismtools:lapis_lazuli_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:leather_chestplate' })
        event.shaped(Item.of('mekanismtools:lapis_lazuli_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:leather_leggings' })
        event.shaped(Item.of('mekanismtools:lapis_lazuli_boots'), ['A A', 'ABA'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:leather_boots' })
        event.shaped(Item.of('minecraft:chainmail_helmet'), ['AAA', 'ABA'], { 'A': 'minecraft:chain', 'B': 'mekanismtools:lapis_lazuli_helmet' })
        event.shaped(Item.of('minecraft:chainmail_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'minecraft:chain', 'B': 'mekanismtools:lapis_lazuli_chestplate' })
        event.shaped(Item.of('minecraft:chainmail_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'minecraft:chain', 'B': 'mekanismtools:lapis_lazuli_leggings' })
        event.shaped(Item.of('minecraft:chainmail_boots'), ['A A', 'ABA'], { 'A': 'minecraft:chain', 'B': 'mekanismtools:lapis_lazuli_boots' })
        event.shaped(Item.of('minecraft:golden_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:chainmail_helmet' })
        event.shaped(Item.of('minecraft:golden_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:chainmail_chestplate' })
        event.shaped(Item.of('minecraft:golden_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:chainmail_leggings' })
        event.shaped(Item.of('minecraft:golden_boots'), ['A A', 'ABA'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:chainmail_boots' })
        event.shaped(Item.of('minecraft:iron_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:iron_plate', 'B': 'minecraft:golden_helmet' })
        event.shaped(Item.of('minecraft:iron_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:iron_plate', 'B': 'minecraft:golden_chestplate' })
        event.shaped(Item.of('minecraft:iron_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:iron_plate', 'B': 'minecraft:golden_leggings' })
        event.shaped(Item.of('minecraft:iron_boots'), ['A A', 'ABA'], { 'A': 'technicresources:iron_plate', 'B': 'minecraft:golden_boots' })
        event.shaped(Item.of('naturesaura:infused_iron_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:infused_iron_plate', 'B': 'minecraft:iron_helmet' })
        event.shaped(Item.of('naturesaura:infused_iron_chest'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:infused_iron_plate', 'B': 'minecraft:iron_chestplate' })
        event.shaped(Item.of('naturesaura:infused_iron_pants'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:infused_iron_plate', 'B': 'minecraft:iron_leggings' })
        event.shaped(Item.of('naturesaura:infused_iron_shoes'), ['A A', 'ABA'], { 'A': 'technicresources:infused_iron_plate', 'B': 'minecraft:iron_boots' })
        event.shaped(Item.of('pneumaticcraft:compressed_iron_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:compressed_iron_plate', 'B': 'naturesaura:infused_iron_helmet' })
        event.shaped(Item.of('pneumaticcraft:compressed_iron_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:compressed_iron_plate', 'B': 'naturesaura:infused_iron_chest' })
        event.shaped(Item.of('pneumaticcraft:compressed_iron_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:compressed_iron_plate', 'B': 'naturesaura:infused_iron_pants' })
        event.shaped(Item.of('pneumaticcraft:compressed_iron_boots'), ['A A', 'ABA'], { 'A': 'technicresources:compressed_iron_plate', 'B': 'naturesaura:infused_iron_shoes' })
        event.shaped(Item.of('mekanismtools:bronze_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:bronze_plate', 'B': 'pneumaticcraft:pneumatic_helmet' })
        event.shaped(Item.of('mekanismtools:bronze_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:bronze_plate', 'B': 'pneumaticcraft:pneumatic_chestplate' })
        event.shaped(Item.of('mekanismtools:bronze_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:bronze_plate', 'B': 'pneumaticcraft:pneumatic_leggings' })
        event.shaped(Item.of('mekanismtools:bronze_boots'), ['A A', 'ABA'], { 'A': 'technicresources:bronze_plate', 'B': 'pneumaticcraft:pneumatic_boots' })
        event.shaped(Item.of('mekanismtools:refined_glowstone_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'mekanismtools:bronze_helmet' })
        event.shaped(Item.of('mekanismtools:refined_glowstone_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'mekanismtools:bronze_chestplate' })
        event.shaped(Item.of('mekanismtools:refined_glowstone_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'mekanismtools:bronze_leggings' })
        event.shaped(Item.of('mekanismtools:refined_glowstone_boots'), ['A A', 'ABA'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'mekanismtools:bronze_boots' })
        event.shaped(Item.of('minecraft:diamond_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:diamond_plate', 'B': 'mekanismtools:refined_glowstone_helmet' })
        event.shaped(Item.of('minecraft:diamond_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:diamond_plate', 'B': 'mekanismtools:refined_glowstone_chestplate' })
        event.shaped(Item.of('minecraft:diamond_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:diamond_plate', 'B': 'mekanismtools:refined_glowstone_leggings' })
        event.shaped(Item.of('minecraft:diamond_boots'), ['A A', 'ABA'], { 'A': 'technicresources:diamond_plate', 'B': 'mekanismtools:refined_glowstone_boots' })
        event.shaped(Item.of('mekanismtools:steel_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:diamond_helmet' })
        event.shaped(Item.of('mekanismtools:steel_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:diamond_chestplate' })
        event.shaped(Item.of('mekanismtools:steel_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:diamond_leggings' })
        event.shaped(Item.of('mekanismtools:steel_boots'), ['A A', 'ABA'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:diamond_boots' })
        event.shaped(Item.of('naturesaura:sky_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:sky_plate', 'B': 'mekanismtools:steel_helmet' })
        event.shaped(Item.of('naturesaura:sky_chest'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:sky_plate', 'B': 'mekanismtools:steel_chestplate' })
        event.shaped(Item.of('naturesaura:sky_pants'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:sky_plate', 'B': 'mekanismtools:steel_leggings' })
        event.shaped(Item.of('naturesaura:sky_shoes'), ['A A', 'ABA'], { 'A': 'technicresources:sky_plate', 'B': 'mekanismtools:steel_boots' })
        event.shaped(Item.of('mekanismtools:osmium_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:osmium_plate', 'B': 'naturesaura:sky_helmet' })
        event.shaped(Item.of('mekanismtools:osmium_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:osmium_plate', 'B': 'naturesaura:sky_chest' })
        event.shaped(Item.of('mekanismtools:osmium_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:osmium_plate', 'B': 'naturesaura:sky_pants' })
        event.shaped(Item.of('mekanismtools:osmium_boots'), ['A A', 'ABA'], { 'A': 'technicresources:osmium_plate', 'B': 'naturesaura:sky_shoes' })
        event.shaped(Item.of('naturesaura:depth_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:depth_plate', 'B': 'mekanismtools:osmium_helmet' })
        event.shaped(Item.of('naturesaura:depth_chest'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:depth_plate', 'B': 'mekanismtools:osmium_chestplate' })
        event.shaped(Item.of('naturesaura:depth_pants'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:depth_plate', 'B': 'mekanismtools:osmium_leggings' })
        event.shaped(Item.of('naturesaura:depth_shoes'), ['A A', 'ABA'], { 'A': 'technicresources:depth_plate', 'B': 'mekanismtools:osmium_boots' })
        event.shaped(Item.of('minecraft:netherite_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:netherite_plate', 'B': 'naturesaura:depth_helmet' })
        event.shaped(Item.of('minecraft:netherite_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:netherite_plate', 'B': 'naturesaura:depth_chest' })
        event.shaped(Item.of('minecraft:netherite_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:netherite_plate', 'B': 'naturesaura:depth_pants' })
        event.shaped(Item.of('minecraft:netherite_boots'), ['A A', 'ABA'], { 'A': 'technicresources:netherite_plate', 'B': 'naturesaura:depth_shoes' })
        event.shaped(Item.of('mekanismtools:refined_obsidian_helmet'), ['AAA', 'ABA'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:netherite_helmet' })
        event.shaped(Item.of('mekanismtools:refined_obsidian_chestplate'), ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:netherite_chestplate' })
        event.shaped(Item.of('mekanismtools:refined_obsidian_leggings'), ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:netherite_leggings' })
        event.shaped(Item.of('mekanismtools:refined_obsidian_boots'), ['A A', 'ABA'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:netherite_boots' })

        //-----------Chapter 0----------------//

        event.shaped(Item.of('technicresources:bedrock_stick'), ['F ', 'F '], { 'F': 'technicresources:bedrock_shard' })
        event.shaped(Item.of('technicresources:bedrock_scraper_head'), ['F ', ' F'], { 'F': 'technicresources:bedrock_shard' })
        event.shaped(Item.of('technicresources:bedrock_scraper'), [' H', 'S '], { 'S': 'technicresources:bedrock_stick', 'H': 'technicresources:bedrock_scraper_head' })
        //Pebbles
        event.shaped(Item.of('minecraft:cobblestone'), ['PP', 'PP'], { 'P': 'technicresources:stone_pebble' })
        event.shaped(Item.of('minecraft:cobbled_deepslate'), ['PP', 'PP'], { 'P': 'technicresources:deepslate_pebble' })
        event.shaped(Item.of('minecraft:granite'), ['PP', 'PP'], { 'P': 'technicresources:granite_pebble' })
        event.shaped(Item.of('minecraft:diorite'), ['PP', 'PP'], { 'P': 'technicresources:diorite_pebble' })
        event.shaped(Item.of('minecraft:andesite'), ['PP', 'PP'], { 'P': 'technicresources:andesite_pebble' })
        event.shaped(Item.of('minecraft:calcite'), ['PP', 'PP'], { 'P': 'technicresources:calcite_pebble' })
        event.shaped(Item.of('minecraft:tuff'), ['PP', 'PP'], { 'P': 'technicresources:tuff_pebble' })
        event.shaped(Item.of('minecraft:netherrack'), ['PP', 'PP'], { 'P': 'technicresources:netherrack_pebble' })
        event.shaped(Item.of('minecraft:blackstone'), ['PP', 'PP'], { 'P': 'technicresources:blackstone_pebble' })
        event.shaped(Item.of('minecraft:basalt'), ['PP', 'PP'], { 'P': 'technicresources:basalt_pebble' })
        event.shaped(Item.of('minecraft:end_stone'), ['PP', 'PP'], { 'P': 'technicresources:endstone_pebble' })

        event.shapeless(Item.of('create:andesite_alloy', 2), ['technicresources:andesite_pebble', 'technicresources:tuff_pebble'])
        event.shapeless(Item.of('create:iron_alloy'), ['technicresources:bedrock_shard', '2x minecraft:iron_nugget'])
        event.shaped(Item.of('create:copper_alloy'), ['WWW', 'WIW', 'WWW'], { 'W': 'minecraft:copper_nugget', 'I': 'create:andesite_alloy' })


        event.shapeless(Item.of('createcasing:stone_cogwheel'), ['create:shaft', 'minecraft:cobblestone'])
        event.shapeless(Item.of('createcasing:stone_large_cogwheel'), ['createcasing:stone_cogwheel', 'minecraft:cobblestone'])
        event.shapeless(Item.of('createcasing:stone_large_cogwheel'), ['create:shaft', 'minecraft:cobblestone', 'minecraft:cobblestone'])
        event.shapeless(Item.of('createcasing:andesite_cogwheel'), ['create:shaft', 'minecraft:andesite'])
        event.shapeless(Item.of('createcasing:andesite_large_cogwheel'), ['createcasing:andesite_cogwheel', 'minecraft:andesite'])
        event.shapeless(Item.of('createcasing:andesite_large_cogwheel'), ['create:shaft', 'minecraft:andesite', 'minecraft:andesite'])
        event.shapeless(Item.of('createcasing:granite_cogwheel'), ['create:shaft', 'minecraft:granite'])
        event.shapeless(Item.of('createcasing:granite_large_cogwheel'), ['createcasing:granite_cogwheel', 'minecraft:granite'])
        event.shapeless(Item.of('createcasing:granite_large_cogwheel'), ['create:shaft', 'minecraft:granite', 'minecraft:granite'])
        event.shapeless(Item.of('createcasing:diorite_cogwheel'), ['create:shaft', 'minecraft:diorite'])
        event.shapeless(Item.of('createcasing:diorite_large_cogwheel'), ['createcasing:diorite_cogwheel', 'minecraft:diorite'])
        event.shapeless(Item.of('createcasing:diorite_large_cogwheel'), ['create:shaft', 'minecraft:diorite', 'minecraft:diorite'])
        event.shapeless(Item.of('createcasing:tuff_cogwheel'), ['create:shaft', 'minecraft:tuff'])
        event.shapeless(Item.of('createcasing:tuff_large_cogwheel'), ['createcasing:tuff_cogwheel', 'minecraft:tuff'])
        event.shapeless(Item.of('createcasing:tuff_large_cogwheel'), ['create:shaft', 'minecraft:tuff', 'minecraft:tuff'])
        event.shapeless(Item.of('createcasing:deepslate_cogwheel'), ['create:shaft', 'minecraft:deepslate'])
        event.shapeless(Item.of('createcasing:deepslate_large_cogwheel'), ['createcasing:deepslate_cogwheel', 'minecraft:deepslate'])
        event.shapeless(Item.of('createcasing:deepslate_large_cogwheel'), ['create:shaft', 'minecraft:deepslate', 'minecraft:deepslate'])
        event.shapeless(Item.of('createcasing:blackstone_cogwheel'), ['create:shaft', 'minecraft:blackstone'])
        event.shapeless(Item.of('createcasing:blackstone_large_cogwheel'), ['createcasing:blackstone_cogwheel', 'minecraft:blackstone'])
        event.shapeless(Item.of('createcasing:blackstone_large_cogwheel'), ['create:shaft', 'minecraft:blackstone', 'minecraft:blackstone'])
        event.shapeless(Item.of('createcasing:basalt_cogwheel'), ['create:shaft', 'minecraft:basalt'])
        event.shapeless(Item.of('createcasing:basalt_large_cogwheel'), ['createcasing:basalt_cogwheel', 'minecraft:basalt'])
        event.shapeless(Item.of('createcasing:basalt_large_cogwheel'), ['create:shaft', 'minecraft:basalt', 'minecraft:basalt'])

        event.shaped(Item.of('technicresources:stone_hammer'), [' C ', ' SC', 'S  '], { 'C': 'minecraft:cobblestone', 'S': "technicresources:deepslate_stick" })
        event.shaped(Item.of('technicresources:metal_hammer'), [' C ', ' SC', 'S  '], { 'C': 'minecraft:iron_ingot', 'S': "technicresources:deepslate_stick" })
        event.shaped(Item.of('technicresources:deepslate_stick', 2), ['D', 'D'], { 'D': 'minecraft:cobbled_deepslate' })

        event.shaped(Item.of('technicresources:small_bedrock'), ['SS', 'SS'], { 'S': 'technicresources:bedrock_shard' })

        event.shaped(Item.of('technicresources:room_upgrader'), ['WWW', 'WIW', 'WWW'], { 'W': 'technicresources:small_bedrock', 'I': 'minecraft:iron_pickaxe' })

        //-------------Chapter 1----------------//

        event.shaped(Item.of('technicresources:breakable_bedrock'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:small_bedrock' })
        event.shaped(Item.of('technicresources:compressed_breakable_bedrock'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:breakable_bedrock' })

        event.shaped(Item.of('technicresources:room_upgrader_2'), ['WWW', 'WIW', 'WWW'], { 'W': 'technicresources:compressed_breakable_bedrock', 'I': 'minecraft:redstone_block' })

        event.shaped(Item.of('minecraft:oak_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:oak_sprout' })
        event.shaped(Item.of('minecraft:spruce_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:spruce_sprout' })
        event.shaped(Item.of('minecraft:dark_oak_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:dark_oak_sprout' })
        event.shaped(Item.of('minecraft:birch_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:birch_sprout' })
        event.shaped(Item.of('minecraft:jungle_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:jungle_sprout' })
        event.shaped(Item.of('minecraft:acacia_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:acacia_sprout' })
        event.shaped(Item.of('minecraft:cherry_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:cherry_sprout' })
        event.shaped(Item.of('minecraft:mangrove_propagule'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:mangrove_sprout' })
        event.shaped(Item.of('ars_nouveau:green_archwood_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:green_archwood_sprout' })
        event.shaped(Item.of('ars_nouveau:red_archwood_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:red_archwood_sprout' })
        event.shaped(Item.of('ars_nouveau:purple_archwood_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:purple_archwood_sprout' })
        event.shaped(Item.of('ars_nouveau:blue_archwood_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:blue_archwood_sprout' })
        event.shaped(Item.of('integrateddynamics:menril_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:menril_sprout' })
        event.shaped(Item.of('naturesaura:ancient_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:ancient_sprout' })
        event.shaped(Item.of('iska_utils:rubber_sapling'), ['WWW', 'WWW', 'WWW'], { 'W': 'technicresources:rubber_sprout' })


        //event.shaped(Item.of('technicresources:bedrock_breaker'), ['WWW', 'WIW', 'WWW'], { 'W': 'technicresources:compressed_wall2', 'I': 'minecraft:diamond_pickaxe' })

        //-------------Mekanism----------------//
        event.shapeless('mekanism:block_antimatter', ['9x mekanism:pellet_antimatter'])
        event.shapeless('9x mekanism:pellet_antimatter', ['mekanism:block_antimatter'])
        event.shapeless('mekanism:block_plutonium', ['9x mekanism:pellet_plutonium'])
        event.shapeless('9x mekanism:pellet_plutonium', ['mekanism:block_plutonium'])
        event.shapeless('mekanism:block_polonium', ['9x mekanism:pellet_polonium'])
        event.shapeless('9x mekanism:pellet_polonium', ['mekanism:block_polonium'])

        //--------RFTools Infused-----------//
        event.shaped('rftoolsbase:dimensionalshard_block', ['AA', 'AA'], { 'A': 'rftoolsbase:dimensionalshard' })
        event.shapeless('4x rftoolsbase:dimensionalshard', ['rftoolsbase:dimensionalshard_block'])
        event.shaped('rftoolsbase:infused_enderpearl', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:ender_pearl' })
        event.shaped('rftoolsbase:infused_diamond', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:diamond' })
        event.shaped('rftoolsbase:infused_emerald', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:emerald' })
        event.shaped('rftoolsbase:infused_redstone', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:redstone' })
        event.shaped('rftoolsbase:infused_quartz', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:quartz' })
        event.shaped('rftoolsbase:infused_lapis_lazuli', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:lapis_lazuli' })
        event.shaped('rftoolsbase:infused_amethyst_shard', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:amethyst_shard' })
        event.shaped('rftoolsbase:infused_iron_ingot', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:iron_ingot' })
        event.shaped('rftoolsbase:infused_gold_ingot', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:gold_ingot' })
        event.shaped('rftoolsbase:infused_copper_ingot', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:copper_ingot' })
        event.shaped('rftoolsbase:infused_netherite_ingot', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:netherite_ingot' })

        //--------Actually Additions-----------//
        event.shapeless('actuallyadditions:empowered_enori_crystal', ['9x actuallyadditions:empowered_enori_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_enori_crystal_shard', ['actuallyadditions:empowered_enori_crystal'])
        event.shapeless('actuallyadditions:empowered_emeradic_crystal', ['9x actuallyadditions:empowered_emeradic_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_emeradic_crystal_shard', ['actuallyadditions:empowered_emeradic_crystal'])
        event.shapeless('actuallyadditions:empowered_void_crystal', ['9x actuallyadditions:empowered_void_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_void_crystal_shard', ['actuallyadditions:empowered_void_crystal'])
        event.shapeless('actuallyadditions:empowered_diamatine_crystal', ['9x actuallyadditions:empowered_diamatine_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_diamatine_crystal_shard', ['actuallyadditions:empowered_diamatine_crystal'])
        event.shapeless('actuallyadditions:empowered_palis_crystal', ['9x actuallyadditions:empowered_palis_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_palis_crystal_shard', ['actuallyadditions:empowered_palis_crystal'])
        event.shapeless('actuallyadditions:empowered_restonia_crystal', ['9x actuallyadditions:empowered_restonia_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_restonia_crystal_shard', ['actuallyadditions:empowered_restonia_crystal'])

        event.shapeless('actuallyadditions:zartiq_crystal', ['9x actuallyadditions:zartiq_crystal_shard'])
        event.shapeless('9x actuallyadditions:zartiq_crystal_shard', ['actuallyadditions:zartiq_crystal'])
        event.shapeless('actuallyadditions:zartiq_crystal_block', ['9x actuallyadditions:zartiq_crystal'])
        event.shapeless('9x actuallyadditions:zartiq_crystal', ['actuallyadditions:zartiq_crystal_block'])
        event.shapeless('actuallyadditions:empowered_zartiq_crystal', ['9x actuallyadditions:empowered_zartiq_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_zartiq_crystal_shard', ['actuallyadditions:empowered_zartiq_crystal'])
        event.shapeless('actuallyadditions:empowered_zartiq_crystal_block', ['9x actuallyadditions:empowered_zartiq_crystal'])
        event.shapeless('9x actuallyadditions:empowered_zartiq_crystal', ['actuallyadditions:empowered_zartiq_crystal_block'])

        event.shapeless('actuallyadditions:inerthet_crystal', ['9x actuallyadditions:inerthet_crystal_shard'])
        event.shapeless('9x actuallyadditions:inerthet_crystal_shard', ['actuallyadditions:inerthet_crystal'])
        event.shapeless('actuallyadditions:inerthet_crystal_block', ['9x actuallyadditions:inerthet_crystal'])
        event.shapeless('9x actuallyadditions:inerthet_crystal', ['actuallyadditions:inerthet_crystal_block'])
        event.shapeless('actuallyadditions:empowered_inerthet_crystal', ['9x actuallyadditions:empowered_inerthet_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_inerthet_crystal_shard', ['actuallyadditions:empowered_inerthet_crystal'])
        event.shapeless('actuallyadditions:empowered_inerthet_crystal_block', ['9x actuallyadditions:empowered_inerthet_crystal'])
        event.shapeless('9x actuallyadditions:empowered_inerthet_crystal', ['actuallyadditions:empowered_inerthet_crystal_block'])

        event.shapeless('actuallyadditions:zerbonkys_crystal', ['9x actuallyadditions:zerbonkys_crystal_shard'])
        event.shapeless('9x actuallyadditions:zerbonkys_crystal_shard', ['actuallyadditions:zerbonkys_crystal'])
        event.shapeless('actuallyadditions:zerbonkys_crystal_block', ['9x actuallyadditions:zerbonkys_crystal'])
        event.shapeless('9x actuallyadditions:zerbonkys_crystal', ['actuallyadditions:zerbonkys_crystal_block'])
        event.shapeless('actuallyadditions:empowered_zerbonkys_crystal', ['9x actuallyadditions:empowered_zerbonkys_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_zerbonkys_crystal_shard', ['actuallyadditions:empowered_zerbonkys_crystal'])
        event.shapeless('actuallyadditions:empowered_zerbonkys_crystal_block', ['9x actuallyadditions:empowered_zerbonkys_crystal'])
        event.shapeless('9x actuallyadditions:empowered_zerbonkys_crystal', ['actuallyadditions:empowered_zerbonkys_crystal_block'])

        event.shapeless('actuallyadditions:zerbon_crystal', ['9x actuallyadditions:zerbon_crystal_shard'])
        event.shapeless('9x actuallyadditions:zerbon_crystal_shard', ['actuallyadditions:zerbon_crystal'])
        event.shapeless('actuallyadditions:zerbon_crystal_block', ['9x actuallyadditions:zerbon_crystal'])
        event.shapeless('9x actuallyadditions:zerbon_crystal', ['actuallyadditions:zerbon_crystal_block'])
        event.shapeless('actuallyadditions:empowered_zerbon_crystal', ['9x actuallyadditions:empowered_zerbon_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_zerbon_crystal_shard', ['actuallyadditions:empowered_zerbon_crystal'])
        event.shapeless('actuallyadditions:empowered_zerbon_crystal_block', ['9x actuallyadditions:empowered_zerbon_crystal'])
        event.shapeless('9x actuallyadditions:empowered_zerbon_crystal', ['actuallyadditions:empowered_zerbon_crystal_block'])

        event.shapeless('actuallyadditions:lectruma_crystal', ['9x actuallyadditions:lectruma_crystal_shard'])
        event.shapeless('9x actuallyadditions:lectruma_crystal_shard', ['actuallyadditions:lectruma_crystal'])
        event.shapeless('actuallyadditions:lectruma_crystal_block', ['9x actuallyadditions:lectruma_crystal'])
        event.shapeless('9x actuallyadditions:lectruma_crystal', ['actuallyadditions:lectruma_crystal_block'])
        event.shapeless('actuallyadditions:empowered_lectruma_crystal', ['9x actuallyadditions:empowered_lectruma_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_lectruma_crystal_shard', ['actuallyadditions:empowered_lectruma_crystal'])
        event.shapeless('actuallyadditions:empowered_lectruma_crystal_block', ['9x actuallyadditions:empowered_lectruma_crystal'])
        event.shapeless('9x actuallyadditions:empowered_lectruma_crystal', ['actuallyadditions:empowered_lectruma_crystal_block'])

        event.shapeless('actuallyadditions:uranima_crystal', ['9x actuallyadditions:uranima_crystal_shard'])
        event.shapeless('9x actuallyadditions:uranima_crystal_shard', ['actuallyadditions:uranima_crystal'])
        event.shapeless('actuallyadditions:uranima_crystal_block', ['9x actuallyadditions:uranima_crystal'])
        event.shapeless('9x actuallyadditions:uranima_crystal', ['actuallyadditions:uranima_crystal_block'])
        event.shapeless('actuallyadditions:empowered_uranima_crystal', ['9x actuallyadditions:empowered_uranima_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_uranima_crystal_shard', ['actuallyadditions:empowered_uranima_crystal'])
        event.shapeless('actuallyadditions:empowered_uranima_crystal_block', ['9x actuallyadditions:empowered_uranima_crystal'])
        event.shapeless('9x actuallyadditions:empowered_uranima_crystal', ['actuallyadditions:empowered_uranima_crystal_block'])

        event.shapeless('actuallyadditions:mosium_crystal', ['9x actuallyadditions:mosium_crystal_shard'])
        event.shapeless('9x actuallyadditions:mosium_crystal_shard', ['actuallyadditions:mosium_crystal'])
        event.shapeless('actuallyadditions:mosium_crystal_block', ['9x actuallyadditions:mosium_crystal'])
        event.shapeless('9x actuallyadditions:mosium_crystal', ['actuallyadditions:mosium_crystal_block'])
        event.shapeless('actuallyadditions:empowered_mosium_crystal', ['9x actuallyadditions:empowered_mosium_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_mosium_crystal_shard', ['actuallyadditions:empowered_mosium_crystal'])
        event.shapeless('actuallyadditions:empowered_mosium_crystal_block', ['9x actuallyadditions:empowered_mosium_crystal'])
        event.shapeless('9x actuallyadditions:empowered_mosium_crystal', ['actuallyadditions:empowered_mosium_crystal_block'])

        event.shapeless('actuallyadditions:richoum_crystal', ['9x actuallyadditions:richoum_crystal_shard'])
        event.shapeless('9x actuallyadditions:richoum_crystal_shard', ['actuallyadditions:richoum_crystal'])
        event.shapeless('actuallyadditions:richoum_crystal_block', ['9x actuallyadditions:richoum_crystal'])
        event.shapeless('9x actuallyadditions:richoum_crystal', ['actuallyadditions:richoum_crystal_block'])
        event.shapeless('actuallyadditions:empowered_richoum_crystal', ['9x actuallyadditions:empowered_richoum_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_richoum_crystal_shard', ['actuallyadditions:empowered_richoum_crystal'])
        event.shapeless('actuallyadditions:empowered_richoum_crystal_block', ['9x actuallyadditions:empowered_richoum_crystal'])
        event.shapeless('9x actuallyadditions:empowered_richoum_crystal', ['actuallyadditions:empowered_richoum_crystal_block'])

        event.shapeless('actuallyadditions:mythase_crystal', ['9x actuallyadditions:mythase_crystal_shard'])
        event.shapeless('9x actuallyadditions:mythase_crystal_shard', ['actuallyadditions:mythase_crystal'])
        event.shapeless('actuallyadditions:mythase_crystal_block', ['9x actuallyadditions:mythase_crystal'])
        event.shapeless('9x actuallyadditions:mythase_crystal', ['actuallyadditions:mythase_crystal_block'])
        event.shapeless('actuallyadditions:empowered_mythase_crystal', ['9x actuallyadditions:empowered_mythase_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_mythase_crystal_shard', ['actuallyadditions:empowered_mythase_crystal'])
        event.shapeless('actuallyadditions:empowered_mythase_crystal_block', ['9x actuallyadditions:empowered_mythase_crystal'])
        event.shapeless('9x actuallyadditions:empowered_mythase_crystal', ['actuallyadditions:empowered_mythase_crystal_block'])

        event.shapeless('actuallyadditions:surcea_crystal', ['9x actuallyadditions:surcea_crystal_shard'])
        event.shapeless('9x actuallyadditions:surcea_crystal_shard', ['actuallyadditions:surcea_crystal'])
        event.shapeless('actuallyadditions:surcea_crystal_block', ['9x actuallyadditions:surcea_crystal'])
        event.shapeless('9x actuallyadditions:surcea_crystal', ['actuallyadditions:surcea_crystal_block'])
        event.shapeless('actuallyadditions:empowered_surcea_crystal', ['9x actuallyadditions:empowered_surcea_crystal_shard'])
        event.shapeless('9x actuallyadditions:empowered_surcea_crystal_shard', ['actuallyadditions:empowered_surcea_crystal'])
        event.shapeless('actuallyadditions:empowered_surcea_crystal_block', ['9x actuallyadditions:empowered_surcea_crystal'])
        event.shapeless('9x actuallyadditions:empowered_surcea_crystal', ['actuallyadditions:empowered_surcea_crystal_block'])

        event.shaped('actuallyadditions:lamp_white', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:enori_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_orange', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:zerbon_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_magenta', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:mythase_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_light_blue', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:diamatine_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_yellow', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:lectruma_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_lime', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:uranima_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_pink', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:surcea_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_gray', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:inerthet_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_light_gray', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:zartiq_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_cyan', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:mosium_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_purple', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:richoum_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_blue', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:palis_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_brown', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:zerbonkys_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_green', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:emeradic_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_red', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:restonia_crystal_shard', 'C': 'actuallyadditions:black_quartz' })
        event.shaped('actuallyadditions:lamp_black', ['ABA', 'BCB', 'ABA'], { 'A': 'minecraft:glowstone', 'B': 'actuallyadditions:void_crystal_shard', 'C': 'actuallyadditions:black_quartz' })

        //--------Applied-----------//
        event.shaped('ae2:cell_component_1k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_mosium_crystal_shard', 'B': 'ae2:charged_certus_quartz_crystal', 'C': 'ae2:quartz_vibrant_glass' })
        event.shaped('ae2:cell_component_4k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_zartiq_crystal_shard', 'B': 'ae2:cell_component_1k', 'C': 'ae2:logic_processor' })
        event.shaped('ae2:cell_component_16k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_inerthet_crystal_shard', 'B': 'ae2:cell_component_4k', 'C': 'ae2:calculation_processor' })
        event.shaped('ae2:cell_component_64k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_zerbonkys_crystal_shard', 'B': 'ae2:cell_component_16k', 'C': 'ae2:engineering_processor' })
        event.shaped('ae2:cell_component_256k', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_zerbon_crystal_shard', 'B': 'ae2:cell_component_64k', 'C': 'extendedae:concurrent_processor' })
        event.shaped('megacells:cell_component_1m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_lectruma_crystal_shard', 'B': 'ae2:cell_component_256k', 'C': 'megacells:accumulation_processor' })
        event.shaped('megacells:cell_component_4m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_uranima_crystal_shard', 'B': 'megacells:cell_component_1m', 'C': 'ae2:logic_processor' })
        event.shaped('megacells:cell_component_16m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_richoum_crystal_shard', 'B': 'megacells:cell_component_4m', 'C': 'ae2:calculation_processor' })
        event.shaped('megacells:cell_component_64m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_mythase_crystal_shard', 'B': 'megacells:cell_component_16m', 'C': 'ae2:engineering_processor' })
        event.shaped('megacells:cell_component_256m', ['ABA', 'BCB', 'ABA'], { 'A': 'actuallyadditions:empowered_surcea_crystal_shard', 'B': 'megacells:cell_component_64m', 'C': 'extendedae:concurrent_processor' })
        event.shaped('advanced_ae:quantum_storage_component', ['ABA', 'BCB', 'ABA'], { 'A': 'ae2:spatial_cell_component_128', 'B': 'megacells:cell_component_256m', 'C': 'advanced_ae:quantum_processor' })
        event.shaped('ae2:spatial_cell_housing', ['ABA', 'B B', 'CCC'], { 'A': 'ae2:quartz_vibrant_glass', 'B': 'minecraft:glowstone_dust', 'C': 'mekanism:ingot_steel' })
        event.shaped('megacells:bulk_item_cell_housing', ['ABA', 'B B', 'CCC'], { 'A': 'ae2:quartz_vibrant_glass', 'B': 'ae2:sky_dust', 'C': 'minecraft:netherite_ingot' })
        event.shaped('megacells:radioactive_chemical_cell_housing', ['ABA', 'B B', 'CDC'], { 'A': 'mekanismgenerators:reactor_glass', 'B': 'ae2:sky_dust', 'C': 'mekanism:hdpe_sheet', 'D': 'mekanism:block_polonium' })
        event.shapeless('ae2:portable_item_cell_housing', ['ae2:item_cell_housing', 'ae2:chest', 'ae2:energy_cell'])
        event.shapeless('ae2:portable_fluid_cell_housing', ['ae2:fluid_cell_housing', 'ae2:chest', 'ae2:energy_cell'])
        event.shapeless('appmek:portable_chemical_cell_housing', ['appmek:chemical_cell_housing', 'ae2:chest', 'ae2:energy_cell'])
        event.shapeless('megacells:portable_item_cell_housing', ['megacells:mega_item_cell_housing', 'ae2:chest', 'ae2:dense_energy_cell'])
        event.shapeless('megacells:portable_fluid_cell_housing', ['megacells:mega_fluid_cell_housing', 'ae2:chest', 'ae2:dense_energy_cell'])
        event.shapeless('megacells:portable_chemical_cell_housing', ['megacells:mega_chemical_cell_housing', 'ae2:chest', 'ae2:dense_energy_cell'])
        event.shapeless('megacells:portable_cell_workbench', ['ae2:item_cell_housing', 'ae2:cell_workbench', 'ae2:singularity'])

        //--------Other-----------//
        event.shaped('createcasing:chorium_block', ['AA', 'AA'], { 'A': 'createcasing:chorium_ingot' })
        event.shapeless('4x createcasing:chorium_ingot', ['createcasing:chorium_block'])

})