
ServerEvents.recipes(event => {
    event.shapeless('rftoolsbase:infused_diamond_block', ['9x rftoolsbase:infused_diamond'])
    event.shapeless('9x rftoolsbase:infused_diamond', ['rftoolsbase:infused_diamond_block'])
    event.shapeless('rftoolsbase:infused_enderpearl_block', ['9x rftoolsbase:infused_enderpearl'])
    event.shapeless('9x rftoolsbase:infused_enderpearl', ['rftoolsbase:infused_enderpearl_block'])
    event.shapeless('rftoolsbase:infused_emerald_block', ['9x rftoolsbase:infused_emerald'])
    event.shapeless('9x rftoolsbase:infused_emerald', ['rftoolsbase:infused_emerald_block'])
    event.shapeless('rftoolsbase:infused_quartz_block', ['9x rftoolsbase:infused_quartz'])
    event.shapeless('9x rftoolsbase:infused_quartz', ['rftoolsbase:infused_quartz_block'])
    event.shapeless('rftoolsbase:infused_redstone_block', ['9x rftoolsbase:infused_redstone'])
    event.shapeless('9x rftoolsbase:infused_redstone', ['rftoolsbase:infused_redstone_block'])
    event.shapeless('rftoolsbase:infused_lapis_lazuli_block', ['9x rftoolsbase:infused_lapis_lazuli'])
    event.shapeless('9x rftoolsbase:infused_lapis_lazuli', ['rftoolsbase:infused_lapis_lazuli_block'])
    event.shapeless('rftoolsbase:infused_iron_block', ['9x rftoolsbase:infused_iron_ingot'])
    event.shapeless('9x rftoolsbase:infused_iron_ingot', ['rftoolsbase:infused_iron_block'])
    event.shapeless('rftoolsbase:infused_gold_block', ['9x rftoolsbase:infused_gold_ingot'])
    event.shapeless('9x rftoolsbase:infused_gold_ingot', ['rftoolsbase:infused_gold_block'])
    event.shapeless('rftoolsbase:infused_copper_block', ['9x rftoolsbase:infused_copper_ingot'])
    event.shapeless('9x rftoolsbase:infused_copper_ingot', ['rftoolsbase:infused_copper_block'])
    event.shapeless('rftoolsbase:infused_netherite_block', ['9x rftoolsbase:infused_netherite_ingot'])
    event.shapeless('9x rftoolsbase:infused_netherite_ingot', ['rftoolsbase:infused_netherite_block'])
    event.shapeless('rftoolsbase:infused_amethyst_block', ['9x rftoolsbase:infused_amethyst_shard'])
    event.shapeless('9x rftoolsbase:infused_amethyst_shard', ['rftoolsbase:infused_amethyst_block'])

})