ServerEvents.tags('block', e => {
    e.add('minecraft:mineable/pickaxe', ['minecraft:crafting_table', 'createcasing:stone_casing', 'createcasing:iron_casing'])
    e.add('technicresources:bedrock_breaker', 'minecraft:bedrock', 'minecraft:torch', 'minecraft:warped_wall_sign', 'ftbquests:barrier', 'minecraft:wall_torch')
    e.add('technicresources:start_break', 'minecraft:torch', 'minecraft:warped_wall_sign', 'ftbquests:barrier', 'minecraft:wall_torch')
    e.add('c:bedrock', ['minecraft:bedrock', 'technicresources:glowrock'])
    e.remove('minecraft:mineable/axe', ['minecraft:crafting_table'])
    e.add('c:storage_blocks', ['actuallyadditions:enori_crystal_block', 'actuallyadditions:emeradic_crystal_block', 'actuallyadditions:void_crystal_block', 'actuallyadditions:diamatine_crystal_block', 'actuallyadditions:palis_crystal_block', 'actuallyadditions:restonia_crystal_block', 'actuallyadditions:empowered_enori_crystal_block', 'actuallyadditions:empowered_emeradic_crystal_block', 'actuallyadditions:empowered_void_crystal_block', 'actuallyadditions:empowered_diamatine_crystal_block', 'actuallyadditions:empowered_palis_crystal_block', 'actuallyadditions:empowered_restonia_crystal_block'])
    e.add('c:storage_blocks', ['naturesaura:infused_iron_block', 'naturesaura:tainted_gold_block', 'naturesaura:sky_ingot_block', 'naturesaura:depth_ingot_block'])
    e.add('c:storage_blocks/infused_iron', ['naturesaura:infused_iron_block'])
    e.add('c:storage_blocks/tainted_gold', ['naturesaura:tainted_gold_block'])
    e.add('c:storage_blocks/sky', ['naturesaura:sky_ingot_block'])
    e.add('c:storage_blocks/depth', ['naturesaura:depth_ingot_block'])
    e.add('c:storage_blocks', ['powah:energized_steel_block', 'powah:blazing_crystal_block', 'powah:niotic_crystal_block', 'powah:spirited_crystal_block', 'powah:nitro_crystal_block'])
    e.add('c:storage_blocks/energized_steel', ['powah:energized_steel_block'])
    e.add('c:storage_blocks/blazing_crystal', ['powah:blazing_crystal_block'])
    e.add('c:storage_blocks/niotic_crystal', ['powah:niotic_crystal_block'])
    e.add('c:storage_blocks/spirited_crystal', ['powah:spirited_crystal_block'])
    e.add('c:storage_blocks/nitro_crystal', ['powah:nitro_crystal_block'])
    e.add('c:storage_blocks', ['avaritia:infinity', 'avaritia:neutron', 'avaritia:crystal_matrix'])
    e.add('c:storage_blocks/infinity', ['avaritia:infinity'])
    e.add('c:storage_blocks/crystal_matrix', ['avaritia:crystal_matrix'])
})

ServerEvents.tags('item', e => {
    e.add('technicresources:pebbles', ['technicresources:blackstone_pebble', 'technicresources:calcite_pebble', 'technicresources:diorite_pebble', 'technicresources:granite_pebble', 'technicresources:andesite_pebble', 'technicresources:stone_pebble', 'technicresources:deepslate_pebble', 'technicresources:tuff_pebble', 'technicresources:netherrack_pebble', 'technicresources:endstone_pebble', 'technicresources:basalt_pebble'])
    e.add('c:storage_blocks', ['actuallyadditions:enori_crystal_block', 'actuallyadditions:emeradic_crystal_block', 'actuallyadditions:void_crystal_block', 'actuallyadditions:diamatine_crystal_block', 'actuallyadditions:palis_crystal_block', 'actuallyadditions:restonia_crystal_block', 'actuallyadditions:empowered_enori_crystal_block', 'actuallyadditions:empowered_emeradic_crystal_block', 'actuallyadditions:empowered_void_crystal_block', 'actuallyadditions:empowered_diamatine_crystal_block', 'actuallyadditions:empowered_palis_crystal_block', 'actuallyadditions:empowered_restonia_crystal_block'])
    e.add('actuallyadditions:crystals/enori', ['actuallyadditions:enori_crystal'])
    e.add('actuallyadditions:crystals/emeradic', ['actuallyadditions:emeradic_crystal'])
    e.add('actuallyadditions:crystals/void', ['actuallyadditions:void_crystal'])
    e.add('actuallyadditions:crystals/diamatine', ['actuallyadditions:diamatine_crystal'])
    e.add('actuallyadditions:crystals/palis', ['actuallyadditions:palis_crystal'])
    e.add('actuallyadditions:crystals/restonia', ['actuallyadditions:restonia_crystal'])
    e.add('actuallyadditions:empowered_crystal_blocks', ['actuallyadditions:empowered_enori_crystal_block', 'actuallyadditions:empowered_emeradic_crystal_block', 'actuallyadditions:empowered_void_crystal_block', 'actuallyadditions:empowered_diamatine_crystal_block', 'actuallyadditions:empowered_palis_crystal_block', 'actuallyadditions:empowered_restonia_crystal_block'])
    e.add('actuallyadditions:empowered_crystals', ['actuallyadditions:empowered_enori_crystal', 'actuallyadditions:empowered_emeradic_crystal', 'actuallyadditions:empowered_void_crystal', 'actuallyadditions:empowered_diamatine_crystal', 'actuallyadditions:empowered_palis_crystal', 'actuallyadditions:empowered_restonia_crystal'])
    e.add('actuallyadditions:empowered_crystals/enori', ['actuallyadditions:empowered_enori_crystal'])
    e.add('actuallyadditions:empowered_crystals/emeradic', ['actuallyadditions:empowered_emeradic_crystal'])
    e.add('actuallyadditions:empowered_crystals/void', ['actuallyadditions:empowered_void_crystal'])
    e.add('actuallyadditions:empowered_crystals/diamatine', ['actuallyadditions:empowered_diamatine_crystal'])
    e.add('actuallyadditions:empowered_crystals/palis', ['actuallyadditions:empowered_palis_crystal'])
    e.add('actuallyadditions:empowered_crystals/restonia', ['actuallyadditions:empowered_restonia_crystal'])

    e.add('actuallyadditions:crystal_shards', ['actuallyadditions:enori_crystal_shard', 'actuallyadditions:emeradic_crystal_shard', 'actuallyadditions:void_crystal_shard', 'actuallyadditions:diamatine_crystal_shard', 'actuallyadditions:palis_crystal_shard', 'actuallyadditions:restonia_crystal_shard'])
    e.add('actuallyadditions:crystal_shards/enori', ['actuallyadditions:enori_crystal_shard'])
    e.add('actuallyadditions:crystal_shards/emeradic', ['actuallyadditions:emeradic_crystal_shard'])
    e.add('actuallyadditions:crystal_shards/void', ['actuallyadditions:void_crystal_shard'])
    e.add('actuallyadditions:crystal_shards/diamatine', ['actuallyadditions:diamatine_crystal_shard'])
    e.add('actuallyadditions:crystal_shards/palis', ['actuallyadditions:palis_crystal_shard'])
    e.add('actuallyadditions:crystal_shards/restonia', ['actuallyadditions:restonia_crystal_shard'])
    e.add('actuallyadditions:empowered_crystal_shards', ['actuallyadditions:empowered_enori_crystal_shard', 'actuallyadditions:empowered_emeradic_crystal_shard', 'actuallyadditions:empowered_void_crystal_shard', 'actuallyadditions:empowered_diamatine_crystal_shard', 'actuallyadditions:empowered_palis_crystal_shard', 'actuallyadditions:empowered_restonia_crystal_shard'])
    e.add('actuallyadditions:empowered_crystal_shards/enori', ['actuallyadditions:empowered_enori_crystal_shard'])
    e.add('actuallyadditions:empowered_crystal_shards/emeradic', ['actuallyadditions:empowered_emeradic_crystal_shard'])
    e.add('actuallyadditions:empowered_crystal_shards/void', ['actuallyadditions:empowered_void_crystal_shard'])
    e.add('actuallyadditions:empowered_crystal_shards/diamatine', ['actuallyadditions:empowered_diamatine_crystal_shard'])
    e.add('actuallyadditions:empowered_crystal_shards/palis', ['actuallyadditions:empowered_palis_crystal_shard'])
    e.add('actuallyadditions:empowered_crystal_shards/restonia', ['actuallyadditions:empowered_restonia_crystal_shard'])

    e.add('c:ingots', ['createcasing:chorium_ingot'])
    e.add('c:ingots/chorium', ['createcasing:chorium_ingot'])
    e.add('c:storage_blocks', ['createcasing:chorium_block'])
    e.add('c:storage_blocks/chorium', ['createcasing:chorium_block'])

    e.removeAllTagsFrom(['create:powdered_obsidian', 'createaddition:diamond_grit', 'pneumaticcraft:copper_nugget', 'create:copper_nugget'])
    e.remove('c:gems/certus_quartz', 'ae2:charged_certus_quartz_crystal')
    e.add('c:gems/charged_certus_quartz', 'ae2:charged_certus_quartz_crystal')

    e.add('c:storage_blocks', ['naturesaura:infused_iron_block', 'naturesaura:tainted_gold_block', 'naturesaura:sky_ingot_block', 'naturesaura:depth_ingot_block'])
    e.add('c:storage_blocks/infused_iron', ['naturesaura:infused_iron_block'])
    e.add('c:storage_blocks/tainted_gold', ['naturesaura:tainted_gold_block'])
    e.add('c:storage_blocks/sky', ['naturesaura:sky_ingot_block'])
    e.add('c:storage_blocks/depth', ['naturesaura:depth_ingot_block'])
    e.add('c:ingots', ['naturesaura:infused_iron', 'naturesaura:tainted_gold', 'naturesaura:sky_ingot', 'naturesaura:depth_ingot'])
    e.add('c:ingots/infused_iron', ['naturesaura:infused_iron'])
    e.add('c:ingots/tainted_gold', ['naturesaura:tainted_gold'])
    e.add('c:ingots/sky', ['naturesaura:sky_ingot'])
    e.add('c:ingots/depth', ['naturesaura:depth_ingot'])

    e.add('c:storage_blocks', ['powah:energized_steel_block', 'powah:blazing_crystal_block', 'powah:niotic_crystal_block', 'powah:spirited_crystal_block', 'powah:nitro_crystal_block'])
    e.add('c:storage_blocks/energized_steel', ['powah:energized_steel_block'])
    e.add('c:storage_blocks/blazing_crystal', ['powah:blazing_crystal_block'])
    e.add('c:storage_blocks/niotic_crystal', ['powah:niotic_crystal_block'])
    e.add('c:storage_blocks/spirited_crystal', ['powah:spirited_crystal_block'])
    e.add('c:storage_blocks/nitro_crystal', ['powah:nitro_crystal_block'])
    e.add('c:ingots', ['powah:steel_energized', 'powah:crystal_blazing', 'powah:crystal_niotic', 'powah:crystal_spirited', 'powah:crystal_nitro'])
    e.add('c:ingots/energized_steel', ['powah:steel_energized'])
    e.add('c:gems', ['powah:steel_energized', 'powah:crystal_blazing', 'powah:crystal_niotic', 'powah:crystal_spirited', 'powah:crystal_nitro'])
    e.add('c:gems/blazing_crystal', ['powah:crystal_blazing'])
    e.add('c:gems/niotic_crystal', ['powah:crystal_niotic'])
    e.add('c:gems/spirited_crystal', ['powah:crystal_spirited'])
    e.add('c:gems/nitro_crystal', ['powah:crystal_nitro'])

    e.add('c:ingots/quantum_alloy', ['advanced_ae:quantum_alloy'])

    e.add('c:ingots', ['create:refined_radiance', 'create:shadow_steel', 'createqol:shadow_radiance'])
    e.add('c:ingots/refined_radiance', ['create:refined_radiance'])
    e.add('c:ingots/shadow_steel', ['create:shadow_steel'])
    e.add('c:ingots/shadow_radiance', ['createqol:shadow_radiance'])

    e.add('c:pellets', ['mekanism:hdpe_pellet', 'mekanism:pellet_polonium', 'mekanism:pellet_plutonium', 'mekanism:pellet_antimatter'])
    e.add('c:pellets/hdpe', ['mekanism:hdpe_pellet'])
    
    e.add('c:storage_blocks', ['avaritia:infinity', 'avaritia:neutron', 'avaritia:crystal_matrix'])
    e.add('c:storage_blocks/infinity', ['avaritia:infinity'])
    e.add('c:storage_blocks/crystal_matrix', ['avaritia:crystal_matrix'])
    
    e.add('c:ingots', ['avaritia:infinity_ingot', 'avaritia:crystal_matrix_ingot'])
    e.add('c:ingots/infinity', ['avaritia:infinity_ingot'])
    e.add('c:ingots/crystal_matrix', ['avaritia:crystal_matrix_ingot'])
})