ServerEvents.tags('block', event => {
    event.add('minecraft:mineable/pickaxe', ['minecraft:crafting_table', 'createcasing:stone_casing', 'createcasing:iron_casing'])
    event.add('technicresources:bedrock_breaker', 'minecraft:bedrock', 'minecraft:torch', 'minecraft:warped_wall_sign', 'ftbquests:barrier', 'minecraft:wall_torch')
    event.add('technicresources:start_break', 'minecraft:torch', 'minecraft:warped_wall_sign', 'ftbquests:barrier', 'minecraft:wall_torch')
    event.add('c:bedrock', ['minecraft:bedrock', 'technicresources:glowrock'])
    event.remove('minecraft:mineable/axe', ['minecraft:crafting_table'])
    event.add('c:storage_blocks', ['actuallyadditions:enori_crystal_block', 'actuallyadditions:emeradic_crystal_block', 'actuallyadditions:void_crystal_block', 'actuallyadditions:diamatine_crystal_block', 'actuallyadditions:palis_crystal_block', 'actuallyadditions:restonia_crystal_block', 'actuallyadditions:empowered_enori_crystal_block', 'actuallyadditions:empowered_emeradic_crystal_block', 'actuallyadditions:empowered_void_crystal_block', 'actuallyadditions:empowered_diamatine_crystal_block', 'actuallyadditions:empowered_palis_crystal_block', 'actuallyadditions:empowered_restonia_crystal_block'])
})

ServerEvents.tags('item', event => {
    event.add('technicresources:pebbles', ['technicresources:blackstone_pebble', 'technicresources:calcite_pebble', 'technicresources:diorite_pebble', 'technicresources:granite_pebble', 'technicresources:andesite_pebble', 'technicresources:stone_pebble', 'technicresources:deepslate_pebble', 'technicresources:tuff_pebble', 'technicresources:netherrack_pebble', 'technicresources:endstone_pebble', 'technicresources:basalt_pebble'])
    event.add('c:storage_blocks', ['actuallyadditions:enori_crystal_block', 'actuallyadditions:emeradic_crystal_block', 'actuallyadditions:void_crystal_block', 'actuallyadditions:diamatine_crystal_block', 'actuallyadditions:palis_crystal_block', 'actuallyadditions:restonia_crystal_block', 'actuallyadditions:empowered_enori_crystal_block', 'actuallyadditions:empowered_emeradic_crystal_block', 'actuallyadditions:empowered_void_crystal_block', 'actuallyadditions:empowered_diamatine_crystal_block', 'actuallyadditions:empowered_palis_crystal_block', 'actuallyadditions:empowered_restonia_crystal_block'])
    event.add('actuallyadditions:crystals/enori', ['actuallyadditions:enori_crystal'])
    event.add('actuallyadditions:crystals/emeradic', ['actuallyadditions:emeradic_crystal'])
    event.add('actuallyadditions:crystals/void', ['actuallyadditions:void_crystal'])
    event.add('actuallyadditions:crystals/diamatine', ['actuallyadditions:diamatine_crystal'])
    event.add('actuallyadditions:crystals/palis', ['actuallyadditions:palis_crystal'])
    event.add('actuallyadditions:crystals/restonia', ['actuallyadditions:restonia_crystal'])
    event.add('actuallyadditions:empowered_crystal_blocks', ['actuallyadditions:empowered_enori_crystal_block', 'actuallyadditions:empowered_emeradic_crystal_block', 'actuallyadditions:empowered_void_crystal_block', 'actuallyadditions:empowered_diamatine_crystal_block', 'actuallyadditions:empowered_palis_crystal_block', 'actuallyadditions:empowered_restonia_crystal_block'])
    event.add('actuallyadditions:empowered_crystals', ['actuallyadditions:empowered_enori_crystal', 'actuallyadditions:empowered_emeradic_crystal', 'actuallyadditions:empowered_void_crystal', 'actuallyadditions:empowered_diamatine_crystal', 'actuallyadditions:empowered_palis_crystal', 'actuallyadditions:empowered_restonia_crystal'])
    event.add('actuallyadditions:empowered_crystals/enori', ['actuallyadditions:empowered_enori_crystal'])
    event.add('actuallyadditions:empowered_crystals/emeradic', ['actuallyadditions:empowered_emeradic_crystal'])
    event.add('actuallyadditions:empowered_crystals/void', ['actuallyadditions:empowered_void_crystal'])
    event.add('actuallyadditions:empowered_crystals/diamatine', ['actuallyadditions:empowered_diamatine_crystal'])
    event.add('actuallyadditions:empowered_crystals/palis', ['actuallyadditions:empowered_palis_crystal'])
    event.add('actuallyadditions:empowered_crystals/restonia', ['actuallyadditions:empowered_restonia_crystal'])

    event.add('actuallyadditions:crystal_shards', ['actuallyadditions:enori_crystal_shard', 'actuallyadditions:emeradic_crystal_shard', 'actuallyadditions:void_crystal_shard', 'actuallyadditions:diamatine_crystal_shard', 'actuallyadditions:palis_crystal_shard', 'actuallyadditions:restonia_crystal_shard'])
    event.add('actuallyadditions:crystal_shards/enori', ['actuallyadditions:enori_crystal_shard'])
    event.add('actuallyadditions:crystal_shards/emeradic', ['actuallyadditions:emeradic_crystal_shard'])
    event.add('actuallyadditions:crystal_shards/void', ['actuallyadditions:void_crystal_shard'])
    event.add('actuallyadditions:crystal_shards/diamatine', ['actuallyadditions:diamatine_crystal_shard'])
    event.add('actuallyadditions:crystal_shards/palis', ['actuallyadditions:palis_crystal_shard'])
    event.add('actuallyadditions:crystal_shards/restonia', ['actuallyadditions:restonia_crystal_shard'])
    event.add('actuallyadditions:empowered_crystal_shards', ['actuallyadditions:empowered_enori_crystal_shard', 'actuallyadditions:empowered_emeradic_crystal_shard', 'actuallyadditions:empowered_void_crystal_shard', 'actuallyadditions:empowered_diamatine_crystal_shard', 'actuallyadditions:empowered_palis_crystal_shard', 'actuallyadditions:empowered_restonia_crystal_shard'])
    event.add('actuallyadditions:empowered_crystal_shards/enori', ['actuallyadditions:empowered_enori_crystal_shard'])
    event.add('actuallyadditions:empowered_crystal_shards/emeradic', ['actuallyadditions:empowered_emeradic_crystal_shard'])
    event.add('actuallyadditions:empowered_crystal_shards/void', ['actuallyadditions:empowered_void_crystal_shard'])
    event.add('actuallyadditions:empowered_crystal_shards/diamatine', ['actuallyadditions:empowered_diamatine_crystal_shard'])
    event.add('actuallyadditions:empowered_crystal_shards/palis', ['actuallyadditions:empowered_palis_crystal_shard'])
    event.add('actuallyadditions:empowered_crystal_shards/restonia', ['actuallyadditions:empowered_restonia_crystal_shard'])

    event.add('c:ingots', ['createcasing:chorium_ingot'])
    event.add('c:ingots/chorium', ['createcasing:chorium_ingot'])
    event.add('c:storage_blocks', ['createcasing:chorium_block'])
    event.add('c:storage_blocks/chorium', ['createcasing:chorium_block'])

    event.removeAllTagsFrom(['create:powdered_obsidian', 'createaddition:diamond_grit'])
})