
ServerEvents.recipes(e => {
    //-----------Chapter 0----------------//
    e.shaped('technicresources:bedrock_stick', ['F ', 'F '], { 'F': 'technicresources:bedrock_shard' })
    e.shaped('technicresources:bedrock_scraper_head', ['F ', ' F'], { 'F': 'technicresources:bedrock_shard' })
    e.shaped('technicresources:bedrock_scraper', [' H', 'S '], { 'S': 'technicresources:bedrock_stick', 'H': 'technicresources:bedrock_scraper_head' })
    e.shaped('minecraft:cobblestone', ['PP', 'PP'], { 'P': 'technicresources:stone_pebble' })
    e.shaped('minecraft:cobbled_deepslate', ['PP', 'PP'], { 'P': 'technicresources:deepslate_pebble' })
    e.shaped('minecraft:granite', ['PP', 'PP'], { 'P': 'technicresources:granite_pebble' })
    e.shaped('minecraft:diorite', ['PP', 'PP'], { 'P': 'technicresources:diorite_pebble' })
    e.shaped('minecraft:andesite', ['PP', 'PP'], { 'P': 'technicresources:andesite_pebble' })
    e.shaped('minecraft:calcite', ['PP', 'PP'], { 'P': 'technicresources:calcite_pebble' })
    e.shaped('minecraft:tuff', ['PP', 'PP'], { 'P': 'technicresources:tuff_pebble' })
    e.shaped('minecraft:netherrack', ['PP', 'PP'], { 'P': 'technicresources:netherrack_pebble' })
    e.shaped('minecraft:blackstone', ['PP', 'PP'], { 'P': 'technicresources:blackstone_pebble' })
    e.shaped('minecraft:basalt', ['PP', 'PP'], { 'P': 'technicresources:basalt_pebble' })
    e.shaped('minecraft:end_stone', ['PP', 'PP'], { 'P': 'technicresources:endstone_pebble' })
    e.shapeless('2x create:andesite_alloy', ['technicresources:andesite_pebble', 'technicresources:tuff_pebble'])
    e.shapeless('create:iron_alloy', ['technicresources:bedrock_shard', '2x minecraft:iron_nugget'])
    e.shaped('create:copper_alloy', ['WWW', 'WIW', 'WWW'], { 'W': 'minecraft:copper_nugget', 'I': 'create:andesite_alloy' })
    e.shapeless('createcasing:stone_cogwheel', ['create:shaft', 'minecraft:cobblestone'])
    e.shapeless('createcasing:stone_large_cogwheel', ['createcasing:stone_cogwheel', 'minecraft:cobblestone'])
    e.shapeless('createcasing:stone_large_cogwheel', ['create:shaft', 'minecraft:cobblestone', 'minecraft:cobblestone'])
    e.shapeless('createcasing:andesite_cogwheel', ['create:shaft', 'minecraft:andesite'])
    e.shapeless('createcasing:andesite_large_cogwheel', ['createcasing:andesite_cogwheel', 'minecraft:andesite'])
    e.shapeless('createcasing:andesite_large_cogwheel', ['create:shaft', 'minecraft:andesite', 'minecraft:andesite'])
    e.shapeless('createcasing:granite_cogwheel', ['create:shaft', 'minecraft:granite'])
    e.shapeless('createcasing:granite_large_cogwheel', ['createcasing:granite_cogwheel', 'minecraft:granite'])
    e.shapeless('createcasing:granite_large_cogwheel', ['create:shaft', 'minecraft:granite', 'minecraft:granite'])
    e.shapeless('createcasing:diorite_cogwheel', ['create:shaft', 'minecraft:diorite'])
    e.shapeless('createcasing:diorite_large_cogwheel', ['createcasing:diorite_cogwheel', 'minecraft:diorite'])
    e.shapeless('createcasing:diorite_large_cogwheel', ['create:shaft', 'minecraft:diorite', 'minecraft:diorite'])
    e.shapeless('createcasing:tuff_cogwheel', ['create:shaft', 'minecraft:tuff'])
    e.shapeless('createcasing:tuff_large_cogwheel', ['createcasing:tuff_cogwheel', 'minecraft:tuff'])
    e.shapeless('createcasing:tuff_large_cogwheel', ['create:shaft', 'minecraft:tuff', 'minecraft:tuff'])
    e.shapeless('createcasing:deepslate_cogwheel', ['create:shaft', 'minecraft:deepslate'])
    e.shapeless('createcasing:deepslate_large_cogwheel', ['createcasing:deepslate_cogwheel', 'minecraft:deepslate'])
    e.shapeless('createcasing:deepslate_large_cogwheel', ['create:shaft', 'minecraft:deepslate', 'minecraft:deepslate'])
    e.shapeless('createcasing:blackstone_cogwheel', ['create:shaft', 'minecraft:blackstone'])
    e.shapeless('createcasing:blackstone_large_cogwheel', ['createcasing:blackstone_cogwheel', 'minecraft:blackstone'])
    e.shapeless('createcasing:blackstone_large_cogwheel', ['create:shaft', 'minecraft:blackstone', 'minecraft:blackstone'])
    e.shapeless('createcasing:basalt_cogwheel', ['create:shaft', 'minecraft:basalt'])
    e.shapeless('createcasing:basalt_large_cogwheel', ['createcasing:basalt_cogwheel', 'minecraft:basalt'])
    e.shapeless('createcasing:basalt_large_cogwheel', ['create:shaft', 'minecraft:basalt', 'minecraft:basalt'])
    e.shaped('technicresources:stone_hammer', [' C ', ' SC', 'S  '], { 'C': 'minecraft:cobblestone', 'S': "technicresources:deepslate_stick" })
    e.shaped('technicresources:metal_hammer', [' C ', ' SC', 'S  '], { 'C': 'minecraft:iron_ingot', 'S': "technicresources:deepslate_stick" })
    e.shaped('2x technicresources:deepslate_stick', ['D', 'D'], { 'D': 'minecraft:cobbled_deepslate' })
    e.shaped('technicresources:small_bedrock', ['SS', 'SS'], { 'S': 'technicresources:bedrock_shard' })
    e.shaped('technicresources:room_upgrader', ['WWW', 'WIW', 'WWW'], { 'W': 'technicresources:small_bedrock', 'I': 'minecraft:iron_pickaxe' })
})