ServerEvents.recipes(e => {
    // Infused
    e.shaped('rftoolsbase:dimensionalshard_block', ['AA', 'AA'], { 'A': 'rftoolsbase:dimensionalshard' })
    e.shapeless('4x rftoolsbase:dimensionalshard', ['rftoolsbase:dimensionalshard_block'])
    e.shaped('rftoolsbase:infused_enderpearl', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:ender_pearl' })
    e.shaped('rftoolsbase:infused_diamond', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:diamond' })
    e.shaped('rftoolsbase:infused_emerald', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:emerald' })
    e.shaped('rftoolsbase:infused_redstone', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:redstone' })
    e.shaped('rftoolsbase:infused_quartz', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:quartz' })
    e.shaped('rftoolsbase:infused_lapis_lazuli', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:lapis_lazuli' })
    e.shaped('rftoolsbase:infused_amethyst_shard', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:amethyst_shard' })
    e.shaped('rftoolsbase:infused_iron_ingot', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:iron_ingot' })
    e.shaped('rftoolsbase:infused_gold_ingot', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:gold_ingot' })
    e.shaped('rftoolsbase:infused_copper_ingot', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:copper_ingot' })
    e.shaped('rftoolsbase:infused_netherite_ingot', ['ABA', 'BCB', 'ABA'], { 'A': 'rftoolsbase:dimensionalshard_block', 'B': 'naturesaura:infused_stone', 'C': 'minecraft:netherite_ingot' })
    e.shapeless('rftoolsbase:infused_diamond_block', ['9x rftoolsbase:infused_diamond'])
    e.shapeless('9x rftoolsbase:infused_diamond', ['rftoolsbase:infused_diamond_block'])
    e.shapeless('rftoolsbase:infused_enderpearl_block', ['9x rftoolsbase:infused_enderpearl'])
    e.shapeless('9x rftoolsbase:infused_enderpearl', ['rftoolsbase:infused_enderpearl_block'])
    e.shapeless('rftoolsbase:infused_emerald_block', ['9x rftoolsbase:infused_emerald'])
    e.shapeless('9x rftoolsbase:infused_emerald', ['rftoolsbase:infused_emerald_block'])
    e.shapeless('rftoolsbase:infused_quartz_block', ['9x rftoolsbase:infused_quartz'])
    e.shapeless('9x rftoolsbase:infused_quartz', ['rftoolsbase:infused_quartz_block'])
    e.shapeless('rftoolsbase:infused_redstone_block', ['9x rftoolsbase:infused_redstone'])
    e.shapeless('9x rftoolsbase:infused_redstone', ['rftoolsbase:infused_redstone_block'])
    e.shapeless('rftoolsbase:infused_lapis_lazuli_block', ['9x rftoolsbase:infused_lapis_lazuli'])
    e.shapeless('9x rftoolsbase:infused_lapis_lazuli', ['rftoolsbase:infused_lapis_lazuli_block'])
    e.shapeless('rftoolsbase:infused_iron_block', ['9x rftoolsbase:infused_iron_ingot'])
    e.shapeless('9x rftoolsbase:infused_iron_ingot', ['rftoolsbase:infused_iron_block'])
    e.shapeless('rftoolsbase:infused_gold_block', ['9x rftoolsbase:infused_gold_ingot'])
    e.shapeless('9x rftoolsbase:infused_gold_ingot', ['rftoolsbase:infused_gold_block'])
    e.shapeless('rftoolsbase:infused_copper_block', ['9x rftoolsbase:infused_copper_ingot'])
    e.shapeless('9x rftoolsbase:infused_copper_ingot', ['rftoolsbase:infused_copper_block'])
    e.shapeless('rftoolsbase:infused_netherite_block', ['9x rftoolsbase:infused_netherite_ingot'])
    e.shapeless('9x rftoolsbase:infused_netherite_ingot', ['rftoolsbase:infused_netherite_block'])
    e.shapeless('rftoolsbase:infused_amethyst_block', ['9x rftoolsbase:infused_amethyst_shard'])
    e.shapeless('9x rftoolsbase:infused_amethyst_shard', ['rftoolsbase:infused_amethyst_block'])
})