StartupEvents.registry('fluid',e =>{
    //e.create('technicresources:minecraft_ore_fluid').textureThick(0x00FF00).bucketColor(0x00FF00).displayName('Minecraft Ore Fluid')
    //e.create('technicresources:molten_redstone').textureThick(0xBA181B).bucketColor(0xBA181B).displayName('Molten Redstone')
    //e.create('technicresources:molten_invarium').textureThick(0x999999).bucketColor(0x999999).displayName('Molten Invarium')
    //e.create('technicresources:molten_diamorium').textureThick(0xCBFF6C).bucketColor(0xCBFF6C).displayName('Molten Diamorium')
    //e.create('technicresources:molten_silicon').thickTexture(0x655D60).bucketColor(0x655D60).displayName('Molten Silicon')
    //e.create('technicresources:electrified_water').textureThin(0x00cdab).bucketColor(0x00cdab).displayName('Electrified Water')
    //e.create('technicresources:mineral_fluid').bucketColor(0xFF5353).textureStill('technicresources:fluid/mineral_still').textureFlowing('technicresources:fluid/mineral_flow').displayName('Mineral Fluid')
    //e.create('technicresources:molten_cobblestone').bucketColor(0xFFAC00).textureStill('technicresources:fluid/molten_cobblestone_still').textureFlowing('technicresources:fluid/molten_cobblestone_flow').displayName('Molten Cobblestone')
    //e.create('technicresources:nether_blood').bucketColor(0xCC0000).textureThick(0xCC0000).displayName('Nether Blood [NYI]')
    //e.create('technicresources:underground_blood').bucketColor(0x999999).textureThin(0x999999).displayName('Underground Blood [NYI]')
    //e.create('technicresources:end_blood').bucketColor(0xEAEACE).textureThick(0xEAEACE).displayName('End Blood [NYI]')
    //e.create('technicresources:impurified_platinum').bucketColor(0x61D0F3).textureThick(0x61D0F3).displayName('Impurified Platinum')
})