
ServerEvents.recipes(e => {
    // Armor
    e.shaped('create:cardboard_helmet', ['AAA', 'A A'], { 'A': 'create:cardboard' })
    e.shaped('create:cardboard_chestplate', ['A A', 'AAA', 'AAA'], { 'A': 'create:cardboard' })
    e.shaped('create:cardboard_leggings', ['AAA', 'A A', 'A A'], { 'A': 'create:cardboard' })
    e.shaped('create:cardboard_boots', ['A A', 'A A'], { 'A': 'create:cardboard' })
    e.shaped('minecraft:leather_helmet', ['AAA', 'ABA'], { 'A': 'minecraft:leather', 'B': 'create:cardboard_helmet' })
    e.shaped('minecraft:leather_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'minecraft:leather', 'B': 'create:cardboard_chestplate' })
    e.shaped('minecraft:leather_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'minecraft:leather', 'B': 'create:cardboard_leggings' })
    e.shaped('minecraft:leather_boots', ['A A', 'ABA'], { 'A': 'minecraft:leather', 'B': 'create:cardboard_boots' })
    e.shaped('mekanismtools:lapis_lazuli_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:leather_helmet' })
    e.shaped('mekanismtools:lapis_lazuli_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:leather_chestplate' })
    e.shaped('mekanismtools:lapis_lazuli_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:leather_leggings' })
    e.shaped('mekanismtools:lapis_lazuli_boots', ['A A', 'ABA'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:leather_boots' })
    e.shaped('minecraft:chainmail_helmet', ['AAA', 'ABA'], { 'A': 'minecraft:chain', 'B': 'mekanismtools:lapis_lazuli_helmet' })
    e.shaped('minecraft:chainmail_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'minecraft:chain', 'B': 'mekanismtools:lapis_lazuli_chestplate' })
    e.shaped('minecraft:chainmail_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'minecraft:chain', 'B': 'mekanismtools:lapis_lazuli_leggings' })
    e.shaped('minecraft:chainmail_boots', ['A A', 'ABA'], { 'A': 'minecraft:chain', 'B': 'mekanismtools:lapis_lazuli_boots' })
    e.shaped('minecraft:golden_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:chainmail_helmet' })
    e.shaped('minecraft:golden_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:chainmail_chestplate' })
    e.shaped('minecraft:golden_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:chainmail_leggings' })
    e.shaped('minecraft:golden_boots', ['A A', 'ABA'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:chainmail_boots' })
    e.shaped('minecraft:iron_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:iron_plate', 'B': 'minecraft:golden_helmet' })
    e.shaped('minecraft:iron_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:iron_plate', 'B': 'minecraft:golden_chestplate' })
    e.shaped('minecraft:iron_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:iron_plate', 'B': 'minecraft:golden_leggings' })
    e.shaped('minecraft:iron_boots', ['A A', 'ABA'], { 'A': 'technicresources:iron_plate', 'B': 'minecraft:golden_boots' })
    e.shaped('naturesaura:infused_iron_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:infused_iron_plate', 'B': 'minecraft:iron_helmet' })
    e.shaped('naturesaura:infused_iron_chest', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:infused_iron_plate', 'B': 'minecraft:iron_chestplate' })
    e.shaped('naturesaura:infused_iron_pants', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:infused_iron_plate', 'B': 'minecraft:iron_leggings' })
    e.shaped('naturesaura:infused_iron_shoes', ['A A', 'ABA'], { 'A': 'technicresources:infused_iron_plate', 'B': 'minecraft:iron_boots' })
    e.shaped('pneumaticcraft:compressed_iron_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:compressed_iron_plate', 'B': 'naturesaura:infused_iron_helmet' })
    e.shaped('pneumaticcraft:compressed_iron_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:compressed_iron_plate', 'B': 'naturesaura:infused_iron_chest' })
    e.shaped('pneumaticcraft:compressed_iron_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:compressed_iron_plate', 'B': 'naturesaura:infused_iron_pants' })
    e.shaped('pneumaticcraft:compressed_iron_boots', ['A A', 'ABA'], { 'A': 'technicresources:compressed_iron_plate', 'B': 'naturesaura:infused_iron_shoes' })
    e.shaped('mekanismtools:bronze_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:bronze_plate', 'B': 'pneumaticcraft:pneumatic_helmet' })
    e.shaped('mekanismtools:bronze_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:bronze_plate', 'B': 'pneumaticcraft:pneumatic_chestplate' })
    e.shaped('mekanismtools:bronze_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:bronze_plate', 'B': 'pneumaticcraft:pneumatic_leggings' })
    e.shaped('mekanismtools:bronze_boots', ['A A', 'ABA'], { 'A': 'technicresources:bronze_plate', 'B': 'pneumaticcraft:pneumatic_boots' })
    e.shaped('mekanismtools:refined_glowstone_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'mekanismtools:bronze_helmet' })
    e.shaped('mekanismtools:refined_glowstone_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'mekanismtools:bronze_chestplate' })
    e.shaped('mekanismtools:refined_glowstone_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'mekanismtools:bronze_leggings' })
    e.shaped('mekanismtools:refined_glowstone_boots', ['A A', 'ABA'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'mekanismtools:bronze_boots' })
    e.shaped('minecraft:diamond_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:diamond_plate', 'B': 'mekanismtools:refined_glowstone_helmet' })
    e.shaped('minecraft:diamond_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:diamond_plate', 'B': 'mekanismtools:refined_glowstone_chestplate' })
    e.shaped('minecraft:diamond_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:diamond_plate', 'B': 'mekanismtools:refined_glowstone_leggings' })
    e.shaped('minecraft:diamond_boots', ['A A', 'ABA'], { 'A': 'technicresources:diamond_plate', 'B': 'mekanismtools:refined_glowstone_boots' })
    e.shaped('mekanismtools:steel_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:diamond_helmet' })
    e.shaped('mekanismtools:steel_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:diamond_chestplate' })
    e.shaped('mekanismtools:steel_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:diamond_leggings' })
    e.shaped('mekanismtools:steel_boots', ['A A', 'ABA'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:diamond_boots' })
    e.shaped('naturesaura:sky_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:sky_plate', 'B': 'mekanismtools:steel_helmet' })
    e.shaped('naturesaura:sky_chest', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:sky_plate', 'B': 'mekanismtools:steel_chestplate' })
    e.shaped('naturesaura:sky_pants', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:sky_plate', 'B': 'mekanismtools:steel_leggings' })
    e.shaped('naturesaura:sky_shoes', ['A A', 'ABA'], { 'A': 'technicresources:sky_plate', 'B': 'mekanismtools:steel_boots' })
    e.shaped('mekanismtools:osmium_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:osmium_plate', 'B': 'naturesaura:sky_helmet' })
    e.shaped('mekanismtools:osmium_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:osmium_plate', 'B': 'naturesaura:sky_chest' })
    e.shaped('mekanismtools:osmium_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:osmium_plate', 'B': 'naturesaura:sky_pants' })
    e.shaped('mekanismtools:osmium_boots', ['A A', 'ABA'], { 'A': 'technicresources:osmium_plate', 'B': 'naturesaura:sky_shoes' })
    e.shaped('naturesaura:depth_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:depth_plate', 'B': 'mekanismtools:osmium_helmet' })
    e.shaped('naturesaura:depth_chest', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:depth_plate', 'B': 'mekanismtools:osmium_chestplate' })
    e.shaped('naturesaura:depth_pants', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:depth_plate', 'B': 'mekanismtools:osmium_leggings' })
    e.shaped('naturesaura:depth_shoes', ['A A', 'ABA'], { 'A': 'technicresources:depth_plate', 'B': 'mekanismtools:osmium_boots' })
    e.shaped('minecraft:netherite_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:netherite_plate', 'B': 'naturesaura:depth_helmet' })
    e.shaped('minecraft:netherite_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:netherite_plate', 'B': 'naturesaura:depth_chest' })
    e.shaped('minecraft:netherite_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:netherite_plate', 'B': 'naturesaura:depth_pants' })
    e.shaped('minecraft:netherite_boots', ['A A', 'ABA'], { 'A': 'technicresources:netherite_plate', 'B': 'naturesaura:depth_shoes' })
    e.shaped('mekanismtools:refined_obsidian_helmet', ['AAA', 'ABA'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:netherite_helmet' })
    e.shaped('mekanismtools:refined_obsidian_chestplate', ['ABA', 'AAA', 'AAA'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:netherite_chestplate' })
    e.shaped('mekanismtools:refined_obsidian_leggings', ['AAA', 'ABA', 'A A'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:netherite_leggings' })
    e.shaped('mekanismtools:refined_obsidian_boots', ['A A', 'ABA'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:netherite_boots' })
})