
ServerEvents.recipes(e => {
        // Dyes
        e.shaped('minecraft:dye_primer', ['A A', ' B '], { 'A': '#c:rods/wooden', 'B': '#minecraft:wooden_slabs' })
        e.shapeless('minecraft:white_dye', ['minecraft:dye_primer', 'minecraft:bone_meal', 'minecraft:bone_meal']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:white_dye', ['minecraft:dye_primer', 'minecraft:lily_of_the_valley']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:light_gray_dye', ['minecraft:dye_primer', 'minecraft:azure_bluet']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:light_gray_dye', ['minecraft:dye_primer', 'minecraft:oxeye_daisy']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:light_gray_dye', ['minecraft:dye_primer', 'minecraft:white_tulip']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:gray_dye', ['minecraft:dye_primer', 'minecraft:charcoal', 'minecraft:charcoal']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:black_dye', ['minecraft:dye_primer', 'minecraft:ink_sac', 'minecraft:ink_sac']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:black_dye', ['minecraft:dye_primer', 'minecraft:wither_rose']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:brown_dye', ['minecraft:dye_primer', 'minecraft:cocoa_beans', 'minecraft:cocoa_beans']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:red_dye', ['minecraft:dye_primer', 'minecraft:beetroot', 'minecraft:beetroot']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:red_dye', ['minecraft:dye_primer', 'minecraft:poppy']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:red_dye', ['minecraft:dye_primer', 'minecraft:red_tulip']).damageIngredient('minecraft:dye_primer')
        e.shapeless('2x minecraft:red_dye', ['minecraft:dye_primer', 'minecraft:rose_bush']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:orange_dye', ['minecraft:dye_primer', 'ars_nouveau:bombegranate_pod', 'ars_nouveau:bombegranate_pod']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:orange_dye', ['minecraft:dye_primer', 'ars_nouveau:wilden_spike', 'ars_nouveau:wilden_spike']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:orange_dye', ['minecraft:dye_primer', 'minecraft:orange_tulip']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:orange_dye', ['minecraft:dye_primer', 'minecraft:torchflower']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:yellow_dye', ['minecraft:dye_primer', '#c:dusts/sulfur', '#c:dusts/sulfur']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:yellow_dye', ['minecraft:dye_primer', 'minecraft:dandelion']).damageIngredient('minecraft:dye_primer')
        e.shapeless('2x minecraft:yellow_dye', ['minecraft:dye_primer', 'minecraft:sunflower']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:pink_dye', ['minecraft:dye_primer', 'ars_nouveau:magebloom', 'ars_nouveau:magebloom']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:pink_dye', ['minecraft:dye_primer', 'minecraft:pink_tulip']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:pink_dye', ['minecraft:dye_primer', 'minecraft:pink_petals']).damageIngredient('minecraft:dye_primer')
        e.shapeless('2x minecraft:pink_dye', ['minecraft:dye_primer', 'minecraft:peony']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:magenta_dye', ['minecraft:dye_primer', 'minecraft:allium']).damageIngredient('minecraft:dye_primer')
        e.shapeless('2x minecraft:magenta_dye', ['minecraft:dye_primer', 'minecraft:lilac']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:purple_dye', ['minecraft:dye_primer', 'ars_nouveau:sourceberry_bush', 'ars_nouveau:sourceberry_bush']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:purple_dye', ['minecraft:dye_primer', 'ars_nouveau:bastion_pod', 'ars_nouveau:bastion_pod']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:blue_dye', ['minecraft:dye_primer', 'minecraft:lapis_lazuli', 'minecraft:lapis_lazuli']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:blue_dye', ['minecraft:dye_primer', 'minecraft:cornflower']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:light_blue_dye', ['minecraft:dye_primer', 'ars_nouveau:frostaya_pod', 'ars_nouveau:frostaya_pod']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:light_blue_dye', ['minecraft:dye_primer', 'minecraft:blue_orchid']).damageIngredient('minecraft:dye_primer')
        e.shapeless('2x minecraft:cyan_dye', ['minecraft:dye_primer', 'minecraft:pitcher_plant']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:green_dye', ['minecraft:dye_primer', 'minecraft:cactus', 'minecraft:cactus']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:lime_dye', ['minecraft:dye_primer', 'ars_nouveau:mendosteen_pod', 'ars_nouveau:mendosteen_pod']).damageIngredient('minecraft:dye_primer')
        e.shapeless('minecraft:lime_dye', ['minecraft:dye_primer', 'minecraft:sea_pickle', 'minecraft:sea_pickle']).damageIngredient('minecraft:dye_primer')
        //--------Other-----------//
        e.shapeless('minecraft:copper_ingot', ['9x minecraft:copper_nugget'])
        e.shapeless('9x minecraft:copper_nugget', ['minecraft:copper_ingot'])
        e.shapeless('minecraft:ender_pearl_block', ['9x minecraft:ender_pearl'])
        e.shapeless('9x minecraft:ender_pearl', ['minecraft:ender_pearl_block'])
})