
ServerEvents.recipes(e => {
    // Tools
    e.shaped('minecraft:wooden_sword', ['A', 'A', 'B'], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:wooden_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:wooden_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:wooden_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:wooden_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:wooden_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:stone_sword', ['A', 'A', 'B'], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:stone_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:stone_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:stone_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:stone_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:stone_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:iron_sword', ['A', 'A', 'B'], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
    e.shaped('minecraft:iron_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
    e.shaped('minecraft:iron_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
    e.shaped('minecraft:iron_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
    e.shaped('minecraft:iron_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:iron_plate', 'B': 'technicresources:deepslate_stick' })
    e.shaped('minecraft:golden_sword', ['A', 'A', 'B'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:golden_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:golden_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:golden_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:golden_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:gold_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:diamond_sword', ['A', 'A', 'B'], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:diamond_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:diamond_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:diamond_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:diamond_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:diamond_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:netherite_sword', ['A', 'A', 'B'], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:netherite_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:netherite_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:netherite_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
    e.shaped('minecraft:netherite_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:netherite_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:nether_quartz_sword', ['A', 'A', 'B'], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:nether_quartz_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:nether_quartz_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:nether_quartz_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:nether_quartz_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:certus_quartz_sword', ['A', 'A', 'B'], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:certus_quartz_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:certus_quartz_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:certus_quartz_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:certus_quartz_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:certus_quartz_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:fluix_sword', ['A', 'A', 'B'], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:fluix_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:fluix_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:fluix_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
    e.shaped('ae2:fluix_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:fluix_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:bronze_sword', ['A', 'A', 'B'], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:bronze_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:bronze_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:bronze_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:bronze_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:bronze_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:lapis_lazuli_sword', ['A', 'A', 'B'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:lapis_lazuli_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:lapis_lazuli_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:lapis_lazuli_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:lapis_lazuli_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:lapis_lazuli_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:osmium_sword', ['A', 'A', 'B'], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:osmium_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:osmium_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:osmium_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:osmium_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:osmium_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_glowstone_sword', ['A', 'A', 'B'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_glowstone_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_glowstone_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_glowstone_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_glowstone_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:refined_glowstone_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_obsidian_sword', ['A', 'A', 'B'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_obsidian_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_obsidian_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_obsidian_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:refined_obsidian_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:refined_obsidian_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:steel_sword', ['A', 'A', 'B'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:steel_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:steel_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:steel_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
    e.shaped('mekanismtools:steel_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:steel_plate', 'B': 'minecraft:stick' })
    e.shaped('naturesaura:infused_iron_sword', ['A', 'A', 'B'], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:infused_iron_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:infused_iron_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:infused_iron_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:infused_iron_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:infused_iron_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:sky_sword', ['A', 'A', 'B'], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:sky_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:sky_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:sky_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:sky_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:sky_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:depth_sword', ['A', 'A', 'B'], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:depth_pickaxe', ['AAA', ' B ', ' B '], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:depth_axe', ['AA', 'AB', ' B'], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:depth_shovel', ['A', 'B', 'B'], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
    e.shaped('naturesaura:depth_hoe', ['AA', ' B', ' B'], { 'A': 'technicresources:depth_plate', 'B': 'naturesaura:ancient_stick' })
})