ServerEvents.recipes(e => {
    e.shaped('8x minecraft:pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:dripstone_block', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:andesite_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:andesite', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:calcite_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:calcite', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:deepslate_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:deepslate', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:diorite_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:diorite', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:smooth_basalt_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:smooth_basalt', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:granite_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:granite', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:stone_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:stone', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:tuff_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:tuff', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:basalt_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:basalt', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:blackstone_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:blackstone', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:endstone_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:end_stone', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:netherrack_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:netherrack', 'D': '#chipped:pointed_dripstone' })
    e.shaped('8x chipped:packed_ice_pointed_dripstone', ['DDD', 'DMD', 'DDD'], { 'M': 'minecraft:packed_ice', 'D': '#chipped:pointed_dripstone' })
})